import { AdjustmentSettings, CropSettings, HSLSettings, ToneCurves, WatermarkSettings, BorderSettings, Project, CollageSettings, ColorManagementSettings } from '../types/editor';

export const DEFAULT_COLOR_MANAGEMENT: ColorManagementSettings = {
  workingSpace: 'display-p3',
  bitDepth: '16-bit',
  softProofEnabled: false,
  proofProfile: 'cmyk-gracol-2006',
  renderingIntent: 'relative-colorimetric',
  simulatePaperWhite: false,
  simulateBlackInk: false,
  paperWhiteTint: '#FAF7ED',
  blackInkDmax: 20,
  gamutWarningEnabled: false,
  gamutWarningColor: 'neon-red',
  gamutThreshold: 85,
  hdrDisplayEnabled: false,
  hdrPeakLuminanceNits: 1000,
  hdrHighlightRecovery: 40,
  hdrSdrGainMap: 50,
  edrBoost: false,
  whitePointIlluminant: 'D65',
  gammaCurve: 'sRGB-2.2',
};

export const DEFAULT_ADJUSTMENTS: AdjustmentSettings = {
  exposure: 0,
  brightness: 0,
  contrast: 0,
  highlights: 0,
  shadows: 0,
  whites: 0,
  blacks: 0,
  gamma: 0,
  midtones: 0,
  hdr: 0,
  brilliance: 0,
  fade: 0,
  blackPoint: 0,
  whitePoint: 100,
  texture: 0,
  temperature: 0,
  tint: 0,
  saturation: 0,
  vibrance: 0,
  clarity: 0,
  sharpness: 0,
  structure: 0,
  microcontrast: 0,
  sharpnessRadius: 1.0,
  sharpnessDetail: 25,
  sharpnessMasking: 0,
  edgeSharpening: 0,
  previewSharpnessMask: false,
  dehaze: 0,
  noiseReduction: 0,
  luminanceNR: 0,
  luminanceDetail: 50,
  colorNoiseReduction: 25,
  colorNoiseDetail: 50,
  colorNoiseSmoothness: 50,
  vignette: 0,
  vignetteMidpoint: 50,
  vignetteFeather: 50,
  filmGrain: 0,
  filmGrainSize: 2,
  splitToning: {
    shadowHue: 210, // Cool blue shadows
    shadowSat: 0,
    highlightHue: 40, // Warm amber highlights
    highlightSat: 0,
    balance: 0,
  },
  globalHue: 0,
  colorBalance: {
    shadows: { cyanRed: 0, magentaGreen: 0, yellowBlue: 0 },
    midtones: { cyanRed: 0, magentaGreen: 0, yellowBlue: 0 },
    highlights: { cyanRed: 0, magentaGreen: 0, yellowBlue: 0 },
  },
  colorWheels: {
    shadows: { hue: 210, sat: 0, lum: 0 },
    midtones: { hue: 45, sat: 0, lum: 0 },
    highlights: { hue: 40, sat: 0, lum: 0 },
    global: { hue: 0, sat: 0, lum: 0 },
  },
  selectiveColors: [],
  colorReplacement: {
    enabled: false,
    sourceHue: 350,
    sourceTolerance: 25,
    targetHue: 180,
    targetSat: 80,
    targetLum: 0,
    feather: 20,
  },
  lutSettings: {
    enabled: false,
    lutId: '',
    lutName: '',
    intensity: 100,
  },
  cameraProfile: {
    profileId: 'adobe-color',
    intensity: 100,
  },
  rawDevelop: {
    wbPreset: 'as-shot',
    kelvin: 5500,
    wbTint: 10,
    highlightRecovery: 0,
    shadowRecovery: 0,
    blackLevel: 0,
    demosaicMethod: 'ahd',
    moireReduction: 0,
  },
  optics: {
    enableDistortionCorrection: false,
    distortion: 0,
    enableCACorrection: false,
    caRedCyan: 0,
    caBlueYellow: 0,
    defringeAmount: 0,
    defringeThreshold: 50,
    enableLensVignette: false,
    lensVignetteAmount: 0,
    lensVignetteMidpoint: 50,
    lensVignetteFeather: 50,
  },
  blur: {
    enabled: false,
    mode: 'lens',
    amount: 30,
    bokehShape: 'circle',
    bokehIntensity: 40,
    bokehThreshold: 75,
    bokehSphericalAberration: 0,
    bokehBladeCurvature: 80,
    motionAngle: 0,
    motionDistance: 25,
    radialCenterX: 0.5,
    radialCenterY: 0.5,
    radialAngle: 15,
    zoomCenterX: 0.5,
    zoomCenterY: 0.5,
    zoomStrength: 25,
    tiltShiftCenterX: 0.5,
    tiltShiftCenterY: 0.5,
    tiltShiftAngle: 0,
    tiltShiftFocusWidth: 25,
    tiltShiftFeather: 35,
    focusDepth: 0.5,
    depthOfField: 0.25,
    apertureFStop: 'f/1.8',
    invertDepth: false,
    selectiveType: 'radial',
    selectiveCenterX: 0.5,
    selectiveCenterY: 0.5,
    selectiveRadius: 0.35,
    selectiveFeather: 0.3,
    selectiveInvert: false,
  },
  aiDepth: {
    enabled: false,
    depthEstimationMethod: 'neural-gradient',
    showDepthMapOverlay: false,
    depthColorMap: 'turbo',
    foregroundThreshold: 0.30,
    backgroundThreshold: 0.65,
    feather: 0.15,
    foreground: {
      exposure: 0,
      contrast: 0,
      highlights: 0,
      shadows: 0,
      temperature: 0,
      tint: 0,
      saturation: 0,
      vibrance: 0,
      clarity: 0,
      texture: 0,
      sharpness: 0,
      blur: 0,
      dehaze: 0,
    },
    subject: {
      exposure: 5,
      contrast: 5,
      highlights: 0,
      shadows: 5,
      temperature: 0,
      tint: 0,
      saturation: 5,
      vibrance: 5,
      clarity: 10,
      texture: 10,
      sharpness: 20,
      blur: 0,
      dehaze: 0,
    },
    background: {
      exposure: -5,
      contrast: -5,
      highlights: -10,
      shadows: 0,
      temperature: 0,
      tint: 0,
      saturation: -5,
      vibrance: -5,
      clarity: -10,
      texture: -10,
      sharpness: 0,
      blur: 25,
      dehaze: -5,
    },
    simulatedFocalDepth: 0.5,
    dofAperture: 0.25,
  },
};

export const DEFAULT_TONE_CURVES: ToneCurves = {
  mode: 'point',
  master: [
    { x: 0, y: 0 },
    { x: 255, y: 255 },
  ],
  red: [
    { x: 0, y: 0 },
    { x: 255, y: 255 },
  ],
  green: [
    { x: 0, y: 0 },
    { x: 255, y: 255 },
  ],
  blue: [
    { x: 0, y: 0 },
    { x: 255, y: 255 },
  ],
  parametric: {
    highlights: 0,
    lights: 0,
    darks: 0,
    shadows: 0,
  },
};

export const DEFAULT_HSL: HSLSettings = {
  red: { hue: 0, saturation: 0, luminance: 0 },
  orange: { hue: 0, saturation: 0, luminance: 0 },
  yellow: { hue: 0, saturation: 0, luminance: 0 },
  green: { hue: 0, saturation: 0, luminance: 0 },
  aqua: { hue: 0, saturation: 0, luminance: 0 },
  blue: { hue: 0, saturation: 0, luminance: 0 },
  purple: { hue: 0, saturation: 0, luminance: 0 },
  magenta: { hue: 0, saturation: 0, luminance: 0 },
};

export const DEFAULT_CROP: CropSettings = {
  x: 0,
  y: 0,
  width: 1,
  height: 1,
  aspectRatio: 'free',
  rotation: 0,
  flipX: false,
  flipY: false,
  perspectiveX: 0,
  perspectiveY: 0,
  expandCanvas: false,
  expandUniform: true,
  expandTop: 0,
  expandBottom: 0,
  expandLeft: 0,
  expandRight: 0,
  bgFillType: 'color',
  bgColor: '#000000',
  bgGradient: {
    type: 'linear',
    color1: '#0f172a',
    color2: '#020617',
    angle: 135,
  },
  blurAmount: 20,
  customResizeEnabled: false,
  lockAspectRatio: true,
};

export const DEFAULT_WATERMARK: WatermarkSettings = {
  enabled: false,
  type: 'text',
  text: '© Lumina Studio Pro',
  font: 'Inter, sans-serif',
  fontSize: 24,
  fontWeight: '600',
  color: '#ffffff',
  opacity: 85,
  position: 'bottom-right',
  customX: 50,
  customY: 50,
  rotation: 0,
  size: 100,
  hasShadow: true,
  shadowColor: 'rgba(0, 0, 0, 0.7)',
  shadowBlur: 6,
  padding: 32,
  logoPreset: 'camera-shutter',
  maintainAspectRatio: true,
  blendMode: 'normal',
  isTiled: false,
  tileSpacingX: 180,
  tileSpacingY: 120,
  tileRotation: -25,
  tileDensity: 'normal',
};

export const DEFAULT_BORDER: BorderSettings = {
  enabled: false,
  type: 'none',
  size: 24,
  color: '#ffffff',
  radius: 0,
  shadowBlur: 16,
  shadowColor: 'rgba(0,0,0,0.5)',
  captionText: '',
};

export const DEFAULT_COLLAGE: CollageSettings = {
  enabled: false,
  mode: 'grid',
  aspectRatio: '1:1',
  layout: 'grid-2x2',
  spacing: 16,
  padding: 24,
  cornerRadius: 12,
  outerBorder: {
    enabled: false,
    size: 16,
    color: '#ffffff',
    style: 'solid',
  },
  background: {
    type: 'solid',
    solidColor: '#0f172a',
    gradient: {
      type: 'linear',
      angle: 135,
      stops: [
        { color: '#0f172a', offset: 0 },
        { color: '#1e1b4b', offset: 1 },
      ],
    },
    pattern: 'polka-dots',
    patternScale: 1.0,
    patternColor: 'rgba(255, 255, 255, 0.08)',
    blurAmount: 20,
  },
  items: [],
  activeItemId: null,
  autoArrangeBy: 'aspect-fit',
};

export const DEFAULT_PROJECT_STATE: Project = {
  id: 'proj_default',
  name: 'Untitled Master',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  image: {
    id: 'img_default',
    name: 'Untitled',
    originalUrl: '',
    width: 0,
    height: 0,
    format: 'jpeg',
    size: 0,
    createdAt: Date.now(),
  },
  currentSettings: DEFAULT_ADJUSTMENTS,
  crop: DEFAULT_CROP,
  toneCurves: DEFAULT_TONE_CURVES,
  hsl: DEFAULT_HSL,
  activePresetId: null,
  presetStrength: 100,
  watermark: DEFAULT_WATERMARK,
  border: DEFAULT_BORDER,
  masks: [],
  layers: [],
  typography: [],
  designElements: [],
  retouchStrokes: [],
  collage: DEFAULT_COLLAGE,
  drawingStrokes: [],
  colorManagement: DEFAULT_COLOR_MANAGEMENT,
  history: [],
  historyIndex: 0,
  snapshots: [],
  cloudSyncStatus: 'local-only',
  cloudRevision: 1,
};
