import { FilterPreset, FilterCategory } from '../types/editor';

export const FILTER_CATEGORIES: FilterCategory[] = [
  'Cinematic',
  'Portrait',
  'Landscape',
  'Street',
  'Food',
  'Travel',
  'Fashion',
  'Vintage',
  'Film',
  'Black & white',
  'Moody',
  'Bright',
  'Warm',
  'Cool',
  'Professional',
  'Social media',
];

export const FILTER_PRESETS: FilterPreset[] = [
  // ============================================================================
  // 1. CINEMATIC
  // ============================================================================
  {
    id: 'cinematic-teal-orange',
    name: 'Urban Teal & Orange',
    category: 'Cinematic',
    description: 'Hollywood blockbuster look separating skin tones with cyan shadows and amber highlights.',
    thumbnailGradient: 'from-teal-600 via-cyan-700 to-amber-500',
    tags: ['hollywood', 'blockbuster', 'teal', 'orange', 'action'],
    settings: {
      exposure: 2,
      contrast: 22,
      highlights: -10,
      shadows: 12,
      temperature: 6,
      tint: -2,
      saturation: 18,
      vibrance: 30,
      clarity: 18,
      sharpness: 24,
      vignette: -16,
      splitToning: {
        shadowHue: 195,
        shadowSat: 38,
        highlightHue: 34,
        highlightSat: 36,
        balance: 5,
      },
    },
    hsl: {
      red: { hue: 0, saturation: 10, luminance: 0 },
      orange: { hue: 4, saturation: 20, luminance: 10 },
      yellow: { hue: -5, saturation: 10, luminance: 5 },
      green: { hue: 20, saturation: -30, luminance: -10 },
      aqua: { hue: 10, saturation: 35, luminance: -5 },
      blue: { hue: -10, saturation: 30, luminance: -10 },
      purple: { hue: 0, saturation: -20, luminance: 0 },
      magenta: { hue: 0, saturation: -15, luminance: 0 },
    },
  },
  {
    id: 'cinematic-cyberpunk',
    name: 'Cyberpunk Neon',
    category: 'Cinematic',
    description: 'Electric cyan-teal shadows with glowing neon magenta and amber highlights.',
    thumbnailGradient: 'from-fuchsia-600 via-purple-700 to-cyan-400',
    tags: ['neon', 'futuristic', 'cyberpunk', 'synthwave', 'night'],
    settings: {
      exposure: 4,
      contrast: 28,
      highlights: 20,
      shadows: -15,
      temperature: -14,
      tint: 28,
      saturation: 32,
      vibrance: 40,
      clarity: 25,
      sharpness: 28,
      vignette: -25,
      splitToning: {
        shadowHue: 190,
        shadowSat: 45,
        highlightHue: 310,
        highlightSat: 40,
        balance: 0,
      },
    },
  },
  {
    id: 'cinematic-blade-runner',
    name: 'Blade Runner Amber',
    category: 'Cinematic',
    description: 'Dystopian golden-orange haze with crushed atmospheric darks and glowing dust.',
    thumbnailGradient: 'from-amber-700 via-orange-600 to-zinc-900',
    tags: ['dystopian', 'amber', 'atmospheric', 'warm', 'glow'],
    settings: {
      exposure: 0,
      contrast: 25,
      highlights: -15,
      shadows: 8,
      temperature: 38,
      tint: 14,
      saturation: 10,
      vibrance: 32,
      clarity: 15,
      dehaze: -12,
      vignette: -30,
      filmGrain: 25,
      splitToning: {
        shadowHue: 30,
        shadowSat: 40,
        highlightHue: 45,
        highlightSat: 45,
        balance: 10,
      },
    },
  },
  {
    id: 'cinematic-matrix-code',
    name: 'Matrix Emerald',
    category: 'Cinematic',
    description: 'Distinctive sci-fi olive-green color cast with lifted midtones and deep contrast.',
    thumbnailGradient: 'from-emerald-950 via-green-800 to-teal-900',
    tags: ['green', 'sci-fi', 'matrix', 'terminal', 'tech'],
    settings: {
      exposure: 0,
      contrast: 20,
      highlights: -18,
      shadows: -5,
      temperature: -10,
      tint: -35,
      saturation: -15,
      vibrance: 10,
      clarity: 22,
      sharpness: 30,
      vignette: -20,
      splitToning: {
        shadowHue: 140,
        shadowSat: 35,
        highlightHue: 125,
        highlightSat: 25,
        balance: -10,
      },
    },
  },
  {
    id: 'cinematic-wes-pastel',
    name: 'Symmetrical Pastel 35mm',
    category: 'Cinematic',
    description: 'Quirky auteur aesthetic with warm mustard yellows, coral pinks, and ultra-flat soft lighting.',
    thumbnailGradient: 'from-amber-200 via-rose-300 to-yellow-300',
    tags: ['wes anderson', 'pastel', 'vintage', 'symmetrical', 'warm'],
    settings: {
      exposure: 12,
      contrast: -24,
      highlights: -30,
      shadows: 36,
      whites: 12,
      blacks: 18,
      temperature: 16,
      tint: 8,
      saturation: 8,
      vibrance: 25,
      clarity: -8,
      sharpness: 12,
      filmGrain: 20,
      splitToning: {
        shadowHue: 40,
        shadowSat: 22,
        highlightHue: 345,
        highlightSat: 20,
        balance: 15,
      },
    },
  },
  {
    id: 'cinematic-dark-noir',
    name: 'Dark Film Noir',
    category: 'Cinematic',
    description: 'Heavily stylized moody film look with muted colors, heavy shadows, and dramatic vignette.',
    thumbnailGradient: 'from-slate-950 via-zinc-800 to-stone-600',
    tags: ['noir', 'moody', 'shadows', 'vignette', 'thriller'],
    settings: {
      exposure: -8,
      contrast: 24,
      highlights: -20,
      shadows: -18,
      whites: -15,
      blacks: 15,
      temperature: -8,
      tint: -4,
      saturation: -32,
      vibrance: -10,
      clarity: 24,
      sharpness: 20,
      vignette: -45,
      filmGrain: 30,
      filmGrainSize: 2,
    },
  },
  {
    id: 'cinematic-imax-gold',
    name: 'IMAX Golden Horizon',
    category: 'Cinematic',
    description: 'Ultra-wide dynamic range cinematic look with rich bronze skin tones and deep blue skies.',
    thumbnailGradient: 'from-amber-500 via-yellow-600 to-blue-900',
    tags: ['imax', 'gold', 'horizon', 'sky', 'epic'],
    settings: {
      exposure: 4,
      contrast: 18,
      highlights: -25,
      shadows: 20,
      whites: 15,
      blacks: -10,
      temperature: 14,
      tint: 4,
      saturation: 15,
      vibrance: 28,
      clarity: 16,
      sharpness: 25,
      splitToning: {
        shadowHue: 215,
        shadowSat: 25,
        highlightHue: 38,
        highlightSat: 30,
        balance: 0,
      },
    },
  },

  // ============================================================================
  // 2. PORTRAIT
  // ============================================================================
  {
    id: 'portrait-editorial-fashion',
    name: 'Editorial High Fashion',
    category: 'Portrait',
    description: 'Polished studio lighting look with smooth skin luminance, controlled highlights, and crisp eye detail.',
    thumbnailGradient: 'from-rose-100 via-stone-200 to-neutral-800',
    tags: ['studio', 'vogue', 'editorial', 'model', 'beauty'],
    settings: {
      exposure: 6,
      contrast: 14,
      highlights: -12,
      shadows: 16,
      whites: 14,
      blacks: -8,
      temperature: 4,
      tint: 6,
      saturation: -4,
      vibrance: 18,
      clarity: 12,
      sharpness: 35,
      filmGrain: 8,
    },
    hsl: {
      red: { hue: 0, saturation: 5, luminance: 6 },
      orange: { hue: 2, saturation: 8, luminance: 12 },
      yellow: { hue: -4, saturation: -10, luminance: 4 },
      green: { hue: 0, saturation: -15, luminance: 0 },
      aqua: { hue: 0, saturation: -10, luminance: 0 },
      blue: { hue: 0, saturation: -10, luminance: 0 },
      purple: { hue: 0, saturation: 0, luminance: 0 },
      magenta: { hue: 0, saturation: 0, luminance: 0 },
    },
  },
  {
    id: 'portrait-velvet-skin',
    name: 'Velvet Skin Glow',
    category: 'Portrait',
    description: 'Soft luminous skin smoothing with gentle peach tones and dreamlike background blur rendition.',
    thumbnailGradient: 'from-rose-200 via-amber-100 to-peach-300',
    tags: ['skin', 'soft', 'beauty', 'glow', 'warm'],
    settings: {
      exposure: 8,
      contrast: -10,
      highlights: -18,
      shadows: 24,
      whites: 8,
      temperature: 8,
      tint: 10,
      saturation: 6,
      vibrance: 22,
      clarity: -6,
      texture: -10,
      sharpness: 20,
    },
  },
  {
    id: 'portrait-golden-glamour',
    name: 'Warm Glamour Hour',
    category: 'Portrait',
    description: 'Sunset portraiture radiating radiant golden backlight with flattering warm complexion tones.',
    thumbnailGradient: 'from-amber-400 via-orange-300 to-rose-400',
    tags: ['golden hour', 'sunset', 'warm', 'glamour', 'backlight'],
    settings: {
      exposure: 10,
      contrast: 8,
      highlights: -22,
      shadows: 28,
      temperature: 24,
      tint: 8,
      saturation: 12,
      vibrance: 28,
      clarity: 8,
      sharpness: 22,
      splitToning: {
        shadowHue: 35,
        shadowSat: 18,
        highlightHue: 48,
        highlightSat: 32,
        balance: 10,
      },
    },
  },
  {
    id: 'portrait-chiaroscuro',
    name: 'Dramatic Chiaroscuro',
    category: 'Portrait',
    description: 'Master painterly Rembrandt lighting with deep shadowy contrast and intense focal highlights.',
    thumbnailGradient: 'from-stone-900 via-amber-950 to-amber-200',
    tags: ['rembrandt', 'dramatic', 'shadows', 'fine art', 'moody'],
    settings: {
      exposure: -4,
      contrast: 32,
      highlights: 14,
      shadows: -22,
      whites: 18,
      blacks: -26,
      temperature: 6,
      tint: -2,
      saturation: -10,
      vibrance: 12,
      clarity: 28,
      sharpness: 38,
      vignette: -35,
    },
  },
  {
    id: 'portrait-high-key-porcelain',
    name: 'Porcelain High Key',
    category: 'Portrait',
    description: 'Ultra-bright, clean studio portrait with milky soft shadows and radiant skin porcelain glow.',
    thumbnailGradient: 'from-white via-slate-100 to-rose-200',
    tags: ['high key', 'porcelain', 'bright', 'white', 'clean'],
    settings: {
      exposure: 16,
      contrast: -15,
      highlights: -25,
      shadows: 35,
      whites: 24,
      blacks: 10,
      temperature: -2,
      tint: 4,
      saturation: -6,
      vibrance: 16,
      clarity: -12,
      sharpness: 24,
    },
  },

  // ============================================================================
  // 3. LANDSCAPE
  // ============================================================================
  {
    id: 'landscape-velvia-50',
    name: 'Fuji Velvia 50 Vibrant',
    category: 'Landscape',
    description: 'Ultra-vivid landscapes with hyper-saturated skies, rich foliage, and punchy micro-contrast.',
    thumbnailGradient: 'from-emerald-500 via-amber-400 to-sky-600',
    tags: ['velvia', 'nature', 'mountains', 'vibrant', 'saturated'],
    settings: {
      exposure: 2,
      contrast: 24,
      highlights: 6,
      shadows: -10,
      whites: 16,
      blacks: -12,
      temperature: 8,
      tint: 4,
      saturation: 36,
      vibrance: 45,
      clarity: 22,
      sharpness: 32,
      dehaze: 12,
    },
  },
  {
    id: 'landscape-nordic-glacier',
    name: 'Nordic Glacier',
    category: 'Landscape',
    description: 'Crisp glacial blues, clean white peaks, deep atmospheric depth, and sharp mountain clarity.',
    thumbnailGradient: 'from-cyan-100 via-blue-200 to-slate-800',
    tags: ['glacier', 'ice', 'mountain', 'cold', 'crisp'],
    settings: {
      exposure: 6,
      contrast: 18,
      highlights: -16,
      shadows: 10,
      whites: 22,
      temperature: -24,
      tint: -6,
      saturation: -10,
      vibrance: 22,
      clarity: 26,
      sharpness: 32,
      dehaze: 18,
    },
  },
  {
    id: 'landscape-golden-hour',
    name: 'Golden Hour Glow',
    category: 'Landscape',
    description: 'Bathing the natural scene in warm honey sunlight with softened contrasts and lush warmth.',
    thumbnailGradient: 'from-amber-500 via-orange-400 to-yellow-200',
    tags: ['sunset', 'golden hour', 'sunlight', 'warm', 'glow'],
    settings: {
      exposure: 8,
      contrast: -6,
      highlights: -18,
      shadows: 24,
      whites: 12,
      temperature: 32,
      tint: 8,
      saturation: 14,
      vibrance: 28,
      clarity: 10,
      sharpness: 16,
      vignette: -12,
      splitToning: {
        shadowHue: 35,
        shadowSat: 25,
        highlightHue: 48,
        highlightSat: 35,
        balance: 20,
      },
    },
  },
  {
    id: 'landscape-moody-forest',
    name: 'Moody Pine Forest',
    category: 'Landscape',
    description: 'Desaturated emerald greens with deep dark shadows, misty highlights, and haunting atmosphere.',
    thumbnailGradient: 'from-emerald-950 via-teal-900 to-stone-400',
    tags: ['forest', 'pine', 'mist', 'dark', 'fog'],
    settings: {
      exposure: -4,
      contrast: 16,
      highlights: -24,
      shadows: -14,
      whites: -10,
      blacks: -18,
      temperature: -10,
      tint: -12,
      saturation: -18,
      vibrance: 12,
      clarity: 22,
      sharpness: 26,
      dehaze: 14,
      vignette: -30,
    },
  },
  {
    id: 'landscape-tropical-lagoon',
    name: 'Tropical Lagoon Turquoise',
    category: 'Landscape',
    description: 'Aquamarine ocean waters, vibrant coral sands, and lush sunlit island foliage.',
    thumbnailGradient: 'from-teal-300 via-cyan-400 to-amber-300',
    tags: ['ocean', 'beach', 'turquoise', 'tropical', 'sea'],
    settings: {
      exposure: 8,
      contrast: 12,
      highlights: -15,
      shadows: 18,
      whites: 15,
      temperature: -4,
      tint: -8,
      saturation: 26,
      vibrance: 38,
      clarity: 18,
      sharpness: 24,
      splitToning: {
        shadowHue: 180,
        shadowSat: 22,
        highlightHue: 50,
        highlightSat: 18,
        balance: -5,
      },
    },
  },

  // ============================================================================
  // 4. STREET
  // ============================================================================
  {
    id: 'street-tokyo-rain',
    name: 'Tokyo Neon Rain',
    category: 'Street',
    description: 'Wet asphalt reflections, vibrant neon glow, deep shadows, and cinematic rainy night grit.',
    thumbnailGradient: 'from-slate-950 via-purple-900 to-cyan-500',
    tags: ['tokyo', 'night', 'rain', 'reflections', 'neon'],
    settings: {
      exposure: 2,
      contrast: 30,
      highlights: 18,
      shadows: -12,
      whites: 15,
      blacks: -20,
      temperature: -12,
      tint: 22,
      saturation: 24,
      vibrance: 36,
      clarity: 26,
      sharpness: 30,
      vignette: -25,
      splitToning: {
        shadowHue: 220,
        shadowSat: 35,
        highlightHue: 320,
        highlightSat: 30,
        balance: 5,
      },
    },
  },
  {
    id: 'street-gritty-asphalt',
    name: 'Gritty Urban Concrete',
    category: 'Street',
    description: 'Punchy street photography style with high midtone contrast, sharp textures, and muted warm tones.',
    thumbnailGradient: 'from-stone-800 via-neutral-600 to-amber-600',
    tags: ['urban', 'gritty', 'concrete', 'street', 'contrast'],
    settings: {
      exposure: 0,
      contrast: 34,
      highlights: -10,
      shadows: -15,
      whites: 20,
      blacks: -22,
      temperature: 4,
      tint: 2,
      saturation: -14,
      vibrance: 12,
      clarity: 32,
      sharpness: 40,
      filmGrain: 24,
      vignette: -18,
    },
  },
  {
    id: 'street-london-overcast',
    name: 'London Overcast Moody',
    category: 'Street',
    description: 'Soft diffused cloudy lighting with desaturated slate tones and pops of red bus color.',
    thumbnailGradient: 'from-slate-400 via-slate-600 to-red-600',
    tags: ['london', 'overcast', 'cloudy', 'subdued', 'moody'],
    settings: {
      exposure: 4,
      contrast: 10,
      highlights: -20,
      shadows: 14,
      temperature: -6,
      tint: 2,
      saturation: -22,
      vibrance: 10,
      clarity: 16,
      sharpness: 22,
      dehaze: 8,
    },
  },
  {
    id: 'street-golden-shadows',
    name: 'Golden Alley Shadows',
    category: 'Street',
    description: 'Hard geometric shadows cut through warm late afternoon sunlight on urban brick and masonry.',
    thumbnailGradient: 'from-amber-600 via-stone-900 to-yellow-500',
    tags: ['shadows', 'afternoon', 'geometry', 'brick', 'warm'],
    settings: {
      exposure: 2,
      contrast: 38,
      highlights: 12,
      shadows: -28,
      whites: 22,
      blacks: -30,
      temperature: 20,
      tint: 6,
      saturation: 16,
      vibrance: 25,
      clarity: 24,
      sharpness: 28,
      vignette: -22,
    },
  },

  // ============================================================================
  // 5. FOOD
  // ============================================================================
  {
    id: 'food-delicious-warmth',
    name: 'Delicious Warmth',
    category: 'Food',
    description: 'Golden culinary warmth, boosting appetites with luscious caramel tones and juicy vibrant hues.',
    thumbnailGradient: 'from-amber-500 via-orange-400 to-rose-400',
    tags: ['culinary', 'warm', 'delicious', 'appetizing', 'restaurant'],
    settings: {
      exposure: 8,
      contrast: 10,
      highlights: -14,
      shadows: 20,
      whites: 12,
      temperature: 18,
      tint: 8,
      saturation: 16,
      vibrance: 32,
      clarity: 14,
      sharpness: 30,
    },
    hsl: {
      red: { hue: 2, saturation: 22, luminance: 8 },
      orange: { hue: -2, saturation: 25, luminance: 12 },
      yellow: { hue: -5, saturation: 20, luminance: 6 },
      green: { hue: 10, saturation: 15, luminance: 4 },
      aqua: { hue: 0, saturation: 0, luminance: 0 },
      blue: { hue: 0, saturation: -10, luminance: 0 },
      purple: { hue: 0, saturation: 0, luminance: 0 },
      magenta: { hue: 0, saturation: 10, luminance: 0 },
    },
  },
  {
    id: 'food-fresh-crispy',
    name: 'Fresh & Crisp Greens',
    category: 'Food',
    description: 'Bright clean daylight highlighting organic textures, dewy salad greens, and vibrant citrus.',
    thumbnailGradient: 'from-emerald-400 via-lime-300 to-amber-200',
    tags: ['fresh', 'crisp', 'salad', 'organic', 'bright'],
    settings: {
      exposure: 10,
      contrast: 12,
      highlights: -18,
      shadows: 16,
      whites: 18,
      temperature: -2,
      tint: -6,
      saturation: 18,
      vibrance: 35,
      clarity: 20,
      sharpness: 35,
    },
  },
  {
    id: 'food-bakery-glow',
    name: 'Bakery Golden Crust',
    category: 'Food',
    description: 'Toasty golden browns, warm butter highlights, and soft rustic café lighting.',
    thumbnailGradient: 'from-amber-700 via-yellow-600 to-amber-200',
    tags: ['bakery', 'bread', 'pastry', 'coffee', 'crust'],
    settings: {
      exposure: 6,
      contrast: 8,
      highlights: -16,
      shadows: 22,
      temperature: 26,
      tint: 12,
      saturation: 12,
      vibrance: 24,
      clarity: 12,
      sharpness: 24,
      splitToning: {
        shadowHue: 32,
        shadowSat: 20,
        highlightHue: 44,
        highlightSat: 28,
        balance: 10,
      },
    },
  },
  {
    id: 'food-moody-gastronomy',
    name: 'Moody Fine Dining',
    category: 'Food',
    description: 'Dark slate background with focused dramatic spotlighting on artisanal gourmet plating.',
    thumbnailGradient: 'from-stone-950 via-zinc-800 to-amber-500',
    tags: ['fine dining', 'gourmet', 'dark', 'chef', 'luxury'],
    settings: {
      exposure: -2,
      contrast: 26,
      highlights: 10,
      shadows: -18,
      whites: 14,
      blacks: -22,
      temperature: 6,
      tint: 2,
      saturation: 10,
      vibrance: 25,
      clarity: 25,
      sharpness: 35,
      vignette: -32,
    },
  },

  // ============================================================================
  // 6. TRAVEL
  // ============================================================================
  {
    id: 'travel-mediterranean',
    name: 'Mediterranean Summer',
    category: 'Travel',
    description: 'Sun-bleached whitewashed architecture, deep azure sea, and terracotta warmth.',
    thumbnailGradient: 'from-sky-400 via-blue-500 to-amber-400',
    tags: ['greece', 'santorini', 'sea', 'summer', 'vacation'],
    settings: {
      exposure: 8,
      contrast: 16,
      highlights: -20,
      shadows: 18,
      whites: 20,
      temperature: 10,
      tint: -2,
      saturation: 22,
      vibrance: 35,
      clarity: 16,
      sharpness: 26,
      splitToning: {
        shadowHue: 210,
        shadowSat: 20,
        highlightHue: 42,
        highlightSat: 24,
        balance: 5,
      },
    },
  },
  {
    id: 'travel-bali-jungle',
    name: 'Bali Emerald Canopy',
    category: 'Travel',
    description: 'Rich tropical green rainforest tones, misty waterfalls, and warm sunbeams through palm leaves.',
    thumbnailGradient: 'from-emerald-800 via-teal-700 to-amber-300',
    tags: ['bali', 'jungle', 'green', 'tropical', 'wanderlust'],
    settings: {
      exposure: 4,
      contrast: 14,
      highlights: -18,
      shadows: 16,
      temperature: 2,
      tint: -10,
      saturation: 24,
      vibrance: 38,
      clarity: 20,
      sharpness: 28,
      dehaze: 10,
    },
  },
  {
    id: 'travel-kyoto-zen',
    name: 'Kyoto Temple Cedar',
    category: 'Travel',
    description: 'Subtle serene Japanese aesthetic with warm cedar woods, muted moss greens, and soft peaceful contrast.',
    thumbnailGradient: 'from-stone-700 via-amber-900 to-emerald-900',
    tags: ['japan', 'kyoto', 'temple', 'zen', 'serene'],
    settings: {
      exposure: 2,
      contrast: -8,
      highlights: -24,
      shadows: 20,
      temperature: 8,
      tint: 4,
      saturation: -12,
      vibrance: 15,
      clarity: 10,
      sharpness: 20,
      filmGrain: 14,
    },
  },
  {
    id: 'travel-sahara-dunes',
    name: 'Sahara Golden Dunes',
    category: 'Travel',
    description: 'Waves of burning golden sand dunes under radiant blue skies with sharp windblown ridges.',
    thumbnailGradient: 'from-amber-600 via-orange-500 to-sky-500',
    tags: ['desert', 'sand', 'dunes', 'warm', 'sahara'],
    settings: {
      exposure: 6,
      contrast: 22,
      highlights: -12,
      shadows: 14,
      whites: 16,
      temperature: 28,
      tint: 6,
      saturation: 20,
      vibrance: 32,
      clarity: 24,
      sharpness: 30,
    },
  },

  // ============================================================================
  // 7. FASHION
  // ============================================================================
  {
    id: 'fashion-vogue-couture',
    name: 'Vogue Haute Couture',
    category: 'Fashion',
    description: 'Striking high fashion editorial contrast, rich fabric textures, and refined color separation.',
    thumbnailGradient: 'from-neutral-900 via-rose-950 to-neutral-200',
    tags: ['vogue', 'runway', 'couture', 'luxury', 'editorial'],
    settings: {
      exposure: 4,
      contrast: 26,
      highlights: -8,
      shadows: 8,
      whites: 18,
      blacks: -14,
      temperature: 2,
      tint: 4,
      saturation: 4,
      vibrance: 20,
      clarity: 18,
      sharpness: 38,
      vignette: -15,
    },
  },
  {
    id: 'fashion-runway-flash',
    name: 'Direct Flash Runway',
    category: 'Fashion',
    description: 'Hard paparazzi direct flash aesthetic with deep background fallout and hyper-crisp garment details.',
    thumbnailGradient: 'from-black via-slate-800 to-white',
    tags: ['flash', 'paparazzi', 'runway', 'party', 'sharp'],
    settings: {
      exposure: 8,
      contrast: 34,
      highlights: 16,
      shadows: -25,
      whites: 26,
      blacks: -32,
      temperature: -4,
      tint: 2,
      saturation: 10,
      vibrance: 22,
      clarity: 30,
      sharpness: 45,
      vignette: -28,
    },
  },
  {
    id: 'fashion-pastel-glam',
    name: 'Pastel Lookbook Glam',
    category: 'Fashion',
    description: 'Dreamy soft pastel lookbook aesthetic with champagne highlights and powder pink hues.',
    thumbnailGradient: 'from-pink-200 via-rose-100 to-amber-100',
    tags: ['lookbook', 'pastel', 'pink', 'soft', 'glam'],
    settings: {
      exposure: 12,
      contrast: -14,
      highlights: -24,
      shadows: 32,
      whites: 14,
      temperature: 6,
      tint: 14,
      saturation: 6,
      vibrance: 24,
      clarity: -6,
      sharpness: 18,
      splitToning: {
        shadowHue: 340,
        shadowSat: 15,
        highlightHue: 35,
        highlightSat: 20,
        balance: 10,
      },
    },
  },

  // ============================================================================
  // 8. VINTAGE
  // ============================================================================
  {
    id: 'vintage-polaroid-70s',
    name: '1970s SX-70 Polaroid',
    category: 'Vintage',
    description: 'Lifted matte faded blacks, nostalgic warm yellow cast, and characteristic chemical soft glow.',
    thumbnailGradient: 'from-yellow-200 via-amber-300 to-stone-400',
    tags: ['polaroid', '70s', 'retro', 'faded', 'matte'],
    settings: {
      exposure: 10,
      contrast: -22,
      highlights: -25,
      shadows: 35,
      whites: -14,
      blacks: 28,
      temperature: 18,
      tint: 12,
      saturation: -12,
      vibrance: 8,
      clarity: -10,
      sharpness: 8,
      filmGrain: 40,
      filmGrainSize: 3,
      vignette: -20,
      splitToning: {
        shadowHue: 45,
        shadowSat: 25,
        highlightHue: 60,
        highlightSat: 20,
        balance: 15,
      },
    },
  },
  {
    id: 'vintage-vhs-80s',
    name: '1980s VHS Cassette',
    category: 'Vintage',
    description: 'Retro magnetic tape video aesthetic with electric magenta tints, analog chromatic noise, and soft lines.',
    thumbnailGradient: 'from-fuchsia-700 via-indigo-800 to-cyan-400',
    tags: ['vhs', '80s', 'analog', 'retro', 'synthwave'],
    settings: {
      exposure: 4,
      contrast: 14,
      highlights: 10,
      shadows: 12,
      temperature: -8,
      tint: 30,
      saturation: 25,
      vibrance: 32,
      clarity: -14,
      sharpness: 10,
      filmGrain: 50,
      filmGrainSize: 3,
      splitToning: {
        shadowHue: 280,
        shadowSat: 35,
        highlightHue: 180,
        highlightSat: 25,
        balance: 0,
      },
    },
  },
  {
    id: 'vintage-technicolor-60s',
    name: '1960s Technicolor 3-Strip',
    category: 'Vintage',
    description: 'Glorious saturated primary colors, vibrant ruby reds, rich cyan skies, and vintage Hollywood glow.',
    thumbnailGradient: 'from-red-600 via-yellow-500 to-blue-600',
    tags: ['technicolor', '60s', 'golden age', 'primary colors', 'saturated'],
    settings: {
      exposure: 6,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      temperature: 8,
      tint: 4,
      saturation: 38,
      vibrance: 45,
      clarity: 14,
      sharpness: 26,
    },
  },
  {
    id: 'vintage-kodachrome-64',
    name: 'Kodachrome 64 Slide',
    category: 'Vintage',
    description: 'Iconic National Geographic slide film with distinctive rich warm reds, deep contrast, and timeless beauty.',
    thumbnailGradient: 'from-red-700 via-amber-600 to-sky-700',
    tags: ['kodachrome', 'slide film', 'national geographic', 'vintage', 'reds'],
    settings: {
      exposure: 2,
      contrast: 28,
      highlights: -12,
      shadows: -8,
      whites: 15,
      blacks: -16,
      temperature: 12,
      tint: 6,
      saturation: 22,
      vibrance: 34,
      clarity: 20,
      sharpness: 30,
      filmGrain: 18,
    },
  },
  {
    id: 'vintage-daguerreotype',
    name: '1850s Daguerreotype Sepia',
    category: 'Vintage',
    description: 'Historical antique silver plate photo with rich warm sepia tone, edge decay, and silver luster.',
    thumbnailGradient: 'from-amber-950 via-yellow-900 to-amber-100',
    tags: ['sepia', 'antique', 'historical', 'daguerreotype', 'monochrome'],
    settings: {
      exposure: 2,
      contrast: 24,
      highlights: -15,
      shadows: 8,
      whites: -10,
      blacks: 12,
      saturation: -95,
      vibrance: -95,
      clarity: 15,
      sharpness: 18,
      filmGrain: 45,
      vignette: -40,
      splitToning: {
        shadowHue: 32,
        shadowSat: 45,
        highlightHue: 42,
        highlightSat: 40,
        balance: 0,
      },
    },
  },

  // ============================================================================
  // 9. FILM
  // ============================================================================
  {
    id: 'film-kodak-portra-400',
    name: 'Kodak Portra 400',
    category: 'Film',
    description: 'Gold standard color negative film: glowing warm skin tones, pastel greens, and creamy highlights.',
    thumbnailGradient: 'from-amber-200 via-orange-300 to-rose-300',
    tags: ['kodak', 'portra 400', 'film', 'skin tones', '35mm'],
    settings: {
      exposure: 5,
      contrast: -8,
      highlights: -15,
      shadows: 18,
      temperature: 12,
      tint: 4,
      saturation: -5,
      vibrance: 14,
      clarity: 6,
      sharpness: 18,
      filmGrain: 22,
      filmGrainSize: 2,
      splitToning: {
        shadowHue: 215,
        shadowSat: 10,
        highlightHue: 42,
        highlightSat: 16,
        balance: 10,
      },
    },
    hsl: {
      red: { hue: 2, saturation: 10, luminance: 4 },
      orange: { hue: -3, saturation: 14, luminance: 8 },
      yellow: { hue: -6, saturation: -8, luminance: 2 },
      green: { hue: 15, saturation: -22, luminance: 6 },
      aqua: { hue: 8, saturation: -10, luminance: 0 },
      blue: { hue: -5, saturation: -14, luminance: 2 },
      purple: { hue: 0, saturation: 0, luminance: 0 },
      magenta: { hue: 0, saturation: 0, luminance: 0 },
    },
  },
  {
    id: 'film-fuji-pro-400h',
    name: 'Fuji Pro 400H',
    category: 'Film',
    description: 'Cool cyan shadows, airy luminous highlights, gentle contrast, and signature minty greens.',
    thumbnailGradient: 'from-teal-200 via-emerald-200 to-cyan-300',
    tags: ['fuji', 'pro 400h', 'film', 'mint', 'cyan'],
    settings: {
      exposure: 8,
      contrast: -12,
      highlights: -20,
      shadows: 22,
      whites: 10,
      temperature: -8,
      tint: -4,
      saturation: 8,
      vibrance: 20,
      clarity: 8,
      sharpness: 20,
      filmGrain: 18,
      filmGrainSize: 2,
      splitToning: {
        shadowHue: 175,
        shadowSat: 14,
        highlightHue: 55,
        highlightSat: 10,
        balance: -5,
      },
    },
  },
  {
    id: 'film-cinestill-800t',
    name: 'CineStill 800T',
    category: 'Film',
    description: 'Motion picture tungsten film for night streets with signature warm halation around lights.',
    thumbnailGradient: 'from-indigo-900 via-teal-700 to-orange-500',
    tags: ['cinestill', '800t', 'tungsten', 'night', 'halation'],
    settings: {
      exposure: 6,
      contrast: 18,
      highlights: 12,
      shadows: 8,
      temperature: -18,
      tint: 10,
      saturation: 16,
      vibrance: 25,
      clarity: 15,
      sharpness: 22,
      vignette: -18,
      filmGrain: 35,
      filmGrainSize: 3,
      splitToning: {
        shadowHue: 200,
        shadowSat: 22,
        highlightHue: 25,
        highlightSat: 28,
        balance: 15,
      },
    },
  },
  {
    id: 'film-kodak-ektar-100',
    name: 'Kodak Ektar 100 Ultra Vivid',
    category: 'Film',
    description: 'Finest grain color negative film with intense saturation, crisp sharpness, and bold cyan-blues.',
    thumbnailGradient: 'from-red-500 via-amber-500 to-blue-600',
    tags: ['ektar', 'kodak', 'vivid', 'fine grain', 'sharp'],
    settings: {
      exposure: 3,
      contrast: 22,
      highlights: -8,
      shadows: 10,
      whites: 16,
      blacks: -10,
      temperature: 6,
      tint: 2,
      saturation: 30,
      vibrance: 40,
      clarity: 22,
      sharpness: 34,
      filmGrain: 12,
    },
  },
  {
    id: 'film-fuji-superia-400',
    name: 'Fujifilm Superia X-TRA 400',
    category: 'Film',
    description: 'Everyday Japanese consumer film with signature emerald greens, crisp contrast, and vibrant magenta accents.',
    thumbnailGradient: 'from-emerald-600 via-green-500 to-fuchsia-600',
    tags: ['superia', 'fuji', 'everyday', 'green', 'consumer'],
    settings: {
      exposure: 4,
      contrast: 14,
      highlights: -12,
      shadows: 12,
      temperature: -6,
      tint: -10,
      saturation: 18,
      vibrance: 28,
      clarity: 16,
      sharpness: 24,
      filmGrain: 28,
    },
  },

  // ============================================================================
  // 10. BLACK & WHITE
  // ============================================================================
  {
    id: 'bw-ilford-hp5',
    name: 'Ilford HP5 Plus 400',
    category: 'Black & white',
    description: 'Classic British monochrome film with punchy midtones, rich silver grain, and wide dynamic latitude.',
    thumbnailGradient: 'from-zinc-900 via-zinc-600 to-zinc-200',
    tags: ['ilford', 'hp5', 'monochrome', 'grain', 'classic'],
    settings: {
      exposure: 4,
      contrast: 26,
      highlights: -10,
      shadows: 14,
      whites: 18,
      blacks: -16,
      saturation: -100,
      vibrance: -100,
      clarity: 22,
      sharpness: 30,
      filmGrain: 45,
      filmGrainSize: 3,
      vignette: -14,
    },
  },
  {
    id: 'bw-leica-monochrom',
    name: 'Leica Monochrom Sensor',
    category: 'Black & white',
    description: 'Ultra-crisp, deep matte blacks and velvety micro-contrast tonal gradations from pure sensor luminance.',
    thumbnailGradient: 'from-black via-neutral-700 to-white',
    tags: ['leica', 'monochrome', 'pure', 'velvet', 'luxury'],
    settings: {
      exposure: 0,
      contrast: 34,
      highlights: 8,
      shadows: -12,
      whites: 22,
      blacks: -24,
      saturation: -100,
      vibrance: -100,
      clarity: 32,
      sharpness: 45,
      filmGrain: 12,
      filmGrainSize: 1,
    },
  },
  {
    id: 'bw-tri-x-400',
    name: 'Kodak Tri-X 400 Gritty',
    category: 'Black & white',
    description: 'Photojournalism legend: aggressive high contrast, heavy organic grain, and deep pitch blacks.',
    thumbnailGradient: 'from-black via-zinc-800 to-zinc-100',
    tags: ['tri-x', 'kodak', 'journalism', 'gritty', 'grain'],
    settings: {
      exposure: 2,
      contrast: 38,
      highlights: 14,
      shadows: -20,
      whites: 24,
      blacks: -30,
      saturation: -100,
      vibrance: -100,
      clarity: 35,
      sharpness: 36,
      filmGrain: 55,
      filmGrainSize: 3,
      vignette: -22,
    },
  },
  {
    id: 'bw-ansel-adams',
    name: 'Ansel Adams Zone System',
    category: 'Black & white',
    description: 'Epic fine art landscape monochrome with maximum dynamic range from Zone 0 pitch black to Zone X brilliant white.',
    thumbnailGradient: 'from-neutral-950 via-neutral-500 to-white',
    tags: ['ansel adams', 'zone system', 'fine art', 'dynamic range', 'landscape'],
    settings: {
      exposure: 2,
      contrast: 22,
      highlights: -18,
      shadows: 20,
      whites: 25,
      blacks: -25,
      saturation: -100,
      vibrance: -100,
      clarity: 28,
      sharpness: 40,
      dehaze: 16,
    },
  },
  {
    id: 'bw-soft-matte',
    name: 'Soft Matte Platinum',
    category: 'Black & white',
    description: 'Delicate low-contrast grayscale with lifted charcoal shadows and smooth silvery highlights.',
    thumbnailGradient: 'from-zinc-800 via-zinc-400 to-zinc-200',
    tags: ['matte', 'platinum', 'soft', 'charcoal', 'portrait'],
    settings: {
      exposure: 6,
      contrast: -18,
      highlights: -22,
      shadows: 30,
      whites: -8,
      blacks: 24,
      saturation: -100,
      vibrance: -100,
      clarity: -6,
      sharpness: 18,
      filmGrain: 20,
    },
  },

  // ============================================================================
  // 11. MOODY
  // ============================================================================
  {
    id: 'moody-nordic-melancholy',
    name: 'Nordic Melancholy',
    category: 'Moody',
    description: 'Cold muted tones, deep evocative shadows, and atmospheric quietness for emotional scenes.',
    thumbnailGradient: 'from-slate-900 via-teal-950 to-stone-500',
    tags: ['melancholy', 'nordic', 'cold', 'shadows', 'cinematic'],
    settings: {
      exposure: -6,
      contrast: 20,
      highlights: -25,
      shadows: -12,
      whites: -15,
      blacks: -15,
      temperature: -16,
      tint: -6,
      saturation: -28,
      vibrance: 8,
      clarity: 20,
      sharpness: 24,
      vignette: -35,
    },
  },
  {
    id: 'moody-dark-cottagecore',
    name: 'Dark Cottagecore & Earth',
    category: 'Moody',
    description: 'Earthy woodland tones, warm mossy greens, muted ochres, and cozy antique shadows.',
    thumbnailGradient: 'from-stone-900 via-amber-950 to-emerald-950',
    tags: ['cottagecore', 'earthy', 'woodland', 'moss', 'antique'],
    settings: {
      exposure: -4,
      contrast: 12,
      highlights: -20,
      shadows: 10,
      temperature: 14,
      tint: 4,
      saturation: -16,
      vibrance: 14,
      clarity: 16,
      sharpness: 22,
      filmGrain: 25,
      vignette: -28,
      splitToning: {
        shadowHue: 40,
        shadowSat: 22,
        highlightHue: 55,
        highlightSat: 18,
        balance: 0,
      },
    },
  },
  {
    id: 'moody-midnight-storm',
    name: 'Midnight Storm Horizon',
    category: 'Moody',
    description: 'Electric deep indigo darks, stormy charcoal clouds, and dramatic lightning clarity.',
    thumbnailGradient: 'from-slate-950 via-indigo-950 to-slate-400',
    tags: ['storm', 'midnight', 'indigo', 'clouds', 'dramatic'],
    settings: {
      exposure: -6,
      contrast: 28,
      highlights: -15,
      shadows: -20,
      temperature: -18,
      tint: 8,
      saturation: -10,
      vibrance: 25,
      clarity: 32,
      sharpness: 35,
      dehaze: 20,
      vignette: -40,
    },
  },

  // ============================================================================
  // 12. BRIGHT
  // ============================================================================
  {
    id: 'bright-clean-daylight',
    name: 'Clean Crisp Daylight',
    category: 'Bright',
    description: 'Luminous sun-kissed exposure with pristine true whites, vibrant clarity, and airy shadows.',
    thumbnailGradient: 'from-white via-sky-100 to-amber-100',
    tags: ['daylight', 'clean', 'crisp', 'bright', 'airy'],
    settings: {
      exposure: 12,
      contrast: 6,
      highlights: -16,
      shadows: 24,
      whites: 20,
      blacks: 6,
      temperature: 2,
      tint: 2,
      saturation: 10,
      vibrance: 25,
      clarity: 14,
      sharpness: 25,
    },
  },
  {
    id: 'bright-sun-drenched',
    name: 'Sun-Drenched Summer',
    category: 'Bright',
    description: 'Basking in bright midday warmth with lifted sunny exposure and sparkling highlight glow.',
    thumbnailGradient: 'from-yellow-200 via-amber-200 to-sky-200',
    tags: ['summer', 'sun', 'bright', 'warm', 'glow'],
    settings: {
      exposure: 15,
      contrast: -6,
      highlights: -24,
      shadows: 30,
      whites: 22,
      temperature: 16,
      tint: 6,
      saturation: 14,
      vibrance: 28,
      clarity: 8,
      sharpness: 20,
    },
  },
  {
    id: 'bright-minimal-white',
    name: 'Airy Minimalist White',
    category: 'Bright',
    description: 'Clean Scandinavian interior aesthetic with bright white surfaces and subtle soft contrast.',
    thumbnailGradient: 'from-white via-neutral-100 to-slate-200',
    tags: ['minimalist', 'interior', 'white', 'scandinavian', 'airy'],
    settings: {
      exposure: 14,
      contrast: -12,
      highlights: -22,
      shadows: 28,
      whites: 26,
      blacks: 12,
      temperature: -4,
      tint: 0,
      saturation: -10,
      vibrance: 12,
      clarity: 10,
      sharpness: 22,
    },
  },

  // ============================================================================
  // 13. WARM
  // ============================================================================
  {
    id: 'warm-tuscan-sun',
    name: 'Tuscan Amber Sun',
    category: 'Warm',
    description: 'Rich terracotta warmth, golden yellow sunbeams, and rustic Italian countryside tones.',
    thumbnailGradient: 'from-amber-500 via-orange-400 to-yellow-300',
    tags: ['tuscany', 'amber', 'golden', 'terracotta', 'sun'],
    settings: {
      exposure: 6,
      contrast: 10,
      highlights: -16,
      shadows: 22,
      temperature: 35,
      tint: 10,
      saturation: 15,
      vibrance: 30,
      clarity: 12,
      sharpness: 22,
      splitToning: {
        shadowHue: 32,
        shadowSat: 28,
        highlightHue: 48,
        highlightSat: 34,
        balance: 10,
      },
    },
  },
  {
    id: 'warm-campfire-ember',
    name: 'Campfire Ember Glow',
    category: 'Warm',
    description: 'Deep fiery orange and red warmth against dark rustic wood and starry night skies.',
    thumbnailGradient: 'from-amber-600 via-red-600 to-stone-900',
    tags: ['campfire', 'ember', 'orange', 'fire', 'cozy'],
    settings: {
      exposure: 2,
      contrast: 22,
      highlights: -10,
      shadows: 14,
      temperature: 42,
      tint: 18,
      saturation: 22,
      vibrance: 36,
      clarity: 18,
      sharpness: 24,
      vignette: -25,
    },
  },
  {
    id: 'warm-caramel-latte',
    name: 'Caramel Macchiato',
    category: 'Warm',
    description: 'Smooth coffee brown and cream tones with comforting café warmth and velvety texture.',
    thumbnailGradient: 'from-amber-700 via-amber-200 to-orange-100',
    tags: ['coffee', 'caramel', 'latte', 'cozy', 'creamy'],
    settings: {
      exposure: 6,
      contrast: -8,
      highlights: -20,
      shadows: 26,
      temperature: 22,
      tint: 12,
      saturation: 4,
      vibrance: 20,
      clarity: 6,
      sharpness: 18,
    },
  },

  // ============================================================================
  // 14. COOL
  // ============================================================================
  {
    id: 'cool-arctic-frost',
    name: 'Arctic Frost & Ice',
    category: 'Cool',
    description: 'Crisp freezing blue tones with pristine white snow highlights and pure polar clarity.',
    thumbnailGradient: 'from-cyan-200 via-blue-300 to-slate-700',
    tags: ['arctic', 'ice', 'frost', 'snow', 'cold'],
    settings: {
      exposure: 8,
      contrast: 14,
      highlights: -18,
      shadows: 12,
      whites: 20,
      temperature: -35,
      tint: -8,
      saturation: 6,
      vibrance: 24,
      clarity: 22,
      sharpness: 30,
      splitToning: {
        shadowHue: 215,
        shadowSat: 30,
        highlightHue: 195,
        highlightSat: 25,
        balance: -5,
      },
    },
  },
  {
    id: 'cool-slate-twilight',
    name: 'Slate Twilight Blue',
    category: 'Cool',
    description: 'Blue hour calming tones after sunset with steel navy backdrops and tranquil soft shadows.',
    thumbnailGradient: 'from-slate-800 via-blue-900 to-indigo-950',
    tags: ['twilight', 'blue hour', 'slate', 'evening', 'calm'],
    settings: {
      exposure: 0,
      contrast: 16,
      highlights: -15,
      shadows: 10,
      temperature: -28,
      tint: 12,
      saturation: 8,
      vibrance: 22,
      clarity: 16,
      sharpness: 24,
      vignette: -18,
    },
  },
  {
    id: 'cool-emerald-mint',
    name: 'Alpine Mint & Spruce',
    category: 'Cool',
    description: 'Refreshing cool mint and spruce green tones with crisp crystalline highlights.',
    thumbnailGradient: 'from-teal-300 via-emerald-400 to-cyan-700',
    tags: ['mint', 'spruce', 'green', 'cool', 'alpine'],
    settings: {
      exposure: 4,
      contrast: 10,
      highlights: -14,
      shadows: 16,
      temperature: -18,
      tint: -20,
      saturation: 14,
      vibrance: 28,
      clarity: 18,
      sharpness: 26,
    },
  },

  // ============================================================================
  // 15. PROFESSIONAL
  // ============================================================================
  {
    id: 'pro-commercial-clean',
    name: 'Commercial Clean & True',
    category: 'Professional',
    description: 'Color-accurate studio calibration for advertising campaigns with neutral white balance and punchy pop.',
    thumbnailGradient: 'from-neutral-100 via-slate-300 to-neutral-700',
    tags: ['commercial', 'advertising', 'accurate', 'true color', 'pro'],
    settings: {
      exposure: 4,
      contrast: 12,
      highlights: -14,
      shadows: 14,
      whites: 12,
      blacks: -8,
      temperature: 0,
      tint: 0,
      saturation: 8,
      vibrance: 18,
      clarity: 16,
      sharpness: 35,
    },
  },
  {
    id: 'pro-corporate-headshot',
    name: 'Corporate Executive Headshot',
    category: 'Professional',
    description: 'Crisp professional portraiture with flattering true skin tones and sharp eye catchlights.',
    thumbnailGradient: 'from-slate-200 via-blue-100 to-slate-800',
    tags: ['headshot', 'corporate', 'linkedin', 'executive', 'portrait'],
    settings: {
      exposure: 6,
      contrast: 10,
      highlights: -12,
      shadows: 18,
      whites: 10,
      blacks: -6,
      temperature: 2,
      tint: 4,
      saturation: 4,
      vibrance: 16,
      clarity: 12,
      sharpness: 32,
    },
  },
  {
    id: 'pro-real-estate-hdr',
    name: 'Real Estate Interior HDR',
    category: 'Professional',
    description: 'Recovered window highlights, bright illuminated interior corners, and straight, clear architecture.',
    thumbnailGradient: 'from-sky-300 via-amber-100 to-stone-400',
    tags: ['real estate', 'interior', 'architecture', 'hdr', 'property'],
    settings: {
      exposure: 8,
      contrast: 8,
      highlights: -35,
      shadows: 38,
      whites: 16,
      blacks: -6,
      temperature: 4,
      tint: -2,
      saturation: 12,
      vibrance: 24,
      clarity: 22,
      sharpness: 32,
      dehaze: 14,
    },
  },
  {
    id: 'pro-ecommerce-white',
    name: 'E-Commerce Pure White',
    category: 'Professional',
    description: 'Product catalog standard: clean background illumination with vibrant accurate product materials.',
    thumbnailGradient: 'from-white via-slate-50 to-neutral-300',
    tags: ['ecommerce', 'catalog', 'product', 'amazon', 'shopify'],
    settings: {
      exposure: 10,
      contrast: 14,
      highlights: -18,
      shadows: 22,
      whites: 26,
      blacks: -4,
      temperature: 0,
      tint: 0,
      saturation: 10,
      vibrance: 20,
      clarity: 18,
      sharpness: 38,
    },
  },

  // ============================================================================
  // 16. SOCIAL MEDIA
  // ============================================================================
  {
    id: 'social-insta-viral',
    name: 'Instagram Viral Clean',
    category: 'Social media',
    description: 'Bright, saturated, high-engagement feed aesthetic that pops off mobile OLED screens.',
    thumbnailGradient: 'from-fuchsia-500 via-orange-400 to-amber-300',
    tags: ['instagram', 'viral', 'feed', 'colorful', 'boost'],
    settings: {
      exposure: 8,
      contrast: 16,
      highlights: -18,
      shadows: 20,
      whites: 18,
      temperature: 6,
      tint: 6,
      saturation: 22,
      vibrance: 36,
      clarity: 18,
      sharpness: 28,
    },
  },
  {
    id: 'social-tiktok-aesthetic',
    name: 'TikTok Warm Aesthetic',
    category: 'Social media',
    description: 'Soft golden influencer aesthetic with creamy tones and flattering warm lighting.',
    thumbnailGradient: 'from-amber-300 via-rose-200 to-yellow-100',
    tags: ['tiktok', 'aesthetic', 'influencer', 'vlogger', 'creamy'],
    settings: {
      exposure: 10,
      contrast: -8,
      highlights: -22,
      shadows: 28,
      whites: 12,
      temperature: 16,
      tint: 10,
      saturation: 8,
      vibrance: 24,
      clarity: 4,
      sharpness: 20,
    },
  },
  {
    id: 'social-influencer-beige',
    name: 'Influencer Minimal Beige',
    category: 'Social media',
    description: 'Curated aesthetic Instagram grid look: muted warm beige, desaturated greens, and chic neutral tones.',
    thumbnailGradient: 'from-stone-300 via-amber-100 to-stone-400',
    tags: ['beige', 'neutral', 'minimal', 'chic', 'influencer'],
    settings: {
      exposure: 6,
      contrast: -12,
      highlights: -24,
      shadows: 28,
      whites: 8,
      temperature: 14,
      tint: 4,
      saturation: -18,
      vibrance: 8,
      clarity: 6,
      sharpness: 18,
      splitToning: {
        shadowHue: 40,
        shadowSat: 16,
        highlightHue: 45,
        highlightSat: 18,
        balance: 10,
      },
    },
    hsl: {
      red: { hue: 0, saturation: -5, luminance: 0 },
      orange: { hue: -2, saturation: 10, luminance: 6 },
      yellow: { hue: -6, saturation: -15, luminance: 2 },
      green: { hue: 20, saturation: -45, luminance: 8 },
      aqua: { hue: 0, saturation: -30, luminance: 0 },
      blue: { hue: 0, saturation: -35, luminance: 0 },
      purple: { hue: 0, saturation: -20, luminance: 0 },
      magenta: { hue: 0, saturation: -15, luminance: 0 },
    },
  },
  {
    id: 'social-sunset-reel',
    name: 'Sunset Reel Glow Boost',
    category: 'Social media',
    description: 'High dynamic range sunset glow for travel & lifestyle reels with deep silhouettes and vibrant skies.',
    thumbnailGradient: 'from-purple-600 via-rose-500 to-amber-400',
    tags: ['sunset', 'reels', 'shorts', 'golden', 'vibrant'],
    settings: {
      exposure: 4,
      contrast: 22,
      highlights: -20,
      shadows: 14,
      whites: 15,
      temperature: 24,
      tint: 14,
      saturation: 26,
      vibrance: 42,
      clarity: 20,
      sharpness: 26,
      splitToning: {
        shadowHue: 280,
        shadowSat: 25,
        highlightHue: 35,
        highlightSat: 35,
        balance: 5,
      },
    },
  },
];

export const MARKETPLACE_PRESETS: FilterPreset[] = [
  {
    id: 'mkt-cyberpunk-neo',
    name: 'Cyberpunk Neo-Tokyo 2099',
    category: 'Cinematic',
    description: 'Electric violet neon highlights, deep cyan midtones, and punchy black contrast.',
    thumbnailGradient: 'from-fuchsia-600 via-indigo-700 to-cyan-500',
    tags: ['cyberpunk', 'neon', 'futuristic', 'night', 'street'],
    author: 'Kenji Sato',
    authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    downloadsCount: 14820,
    rating: 4.95,
    likesCount: 3420,
    isCommunity: true,
    recommendedFor: ['Night Streets', 'Neon Cityscapes', 'Cyberpunk Portraits'],
    settings: {
      exposure: 4,
      contrast: 28,
      highlights: -18,
      shadows: 14,
      whites: 8,
      blacks: -16,
      temperature: -12,
      tint: 18,
      saturation: 24,
      vibrance: 38,
      clarity: 22,
      sharpness: 30,
      vignette: -20,
      splitToning: {
        shadowHue: 195,
        shadowSat: 44,
        highlightHue: 310,
        highlightSat: 42,
        balance: 10,
      },
    },
    hsl: {
      blue: { hue: -10, saturation: 35, luminance: -5 },
      aqua: { hue: -15, saturation: 40, luminance: 10 },
      purple: { hue: 15, saturation: 45, luminance: 5 },
      magenta: { hue: 20, saturation: 50, luminance: 8 },
    },
  },
  {
    id: 'mkt-amalfi-sun',
    name: 'Amalfi Coast Golden Horizon',
    category: 'Travel',
    description: 'Warm Mediterranean terracotta glow, turquoise marine clarity, and breezy highlights.',
    thumbnailGradient: 'from-amber-500 via-orange-500 to-sky-400',
    tags: ['summer', 'italy', 'coastal', 'golden hour', 'travel'],
    author: 'Elena Rossi',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    downloadsCount: 21350,
    rating: 4.98,
    likesCount: 5210,
    isCommunity: true,
    recommendedFor: ['Summer Travel', 'Beach Landscapes', 'Golden Hour Portraits'],
    settings: {
      exposure: 6,
      contrast: 14,
      highlights: -12,
      shadows: 18,
      whites: 12,
      blacks: -6,
      temperature: 18,
      tint: -4,
      saturation: 16,
      vibrance: 32,
      clarity: 14,
      sharpness: 22,
      vignette: -10,
      splitToning: {
        shadowHue: 210,
        shadowSat: 20,
        highlightHue: 42,
        highlightSat: 36,
        balance: 15,
      },
    },
    hsl: {
      yellow: { hue: 6, saturation: 22, luminance: 8 },
      orange: { hue: 2, saturation: 18, luminance: 6 },
      blue: { hue: -8, saturation: 28, luminance: 12 },
      aqua: { hue: 5, saturation: 30, luminance: 15 },
    },
  },
  {
    id: 'mkt-kodak-gold-200',
    name: 'Kodak Gold 200 Warm Film',
    category: 'Film',
    description: 'Authentic 90s point-and-shoot film with warm golden yellow undertones and organic grain.',
    thumbnailGradient: 'from-amber-400 via-yellow-500 to-red-500',
    tags: ['kodak', 'film', 'analog', 'vintage', '35mm'],
    author: 'Arthur Vance',
    authorAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&auto=format&fit=crop&q=80',
    downloadsCount: 18900,
    rating: 4.92,
    likesCount: 4120,
    isCommunity: true,
    recommendedFor: ['Street Photography', 'Casual Portraits', 'Sunny Days'],
    settings: {
      exposure: 3,
      contrast: 16,
      highlights: -8,
      shadows: 10,
      temperature: 14,
      tint: 2,
      saturation: 12,
      vibrance: 22,
      clarity: 10,
      filmGrain: 36,
      vignette: -14,
      splitToning: {
        shadowHue: 50,
        shadowSat: 24,
        highlightHue: 38,
        highlightSat: 28,
        balance: 10,
      },
    },
  },
  {
    id: 'mkt-vogue-editorial',
    name: 'Vogue Haute Editorial',
    category: 'Fashion',
    description: 'High-contrast studio lighting, refined matte blacks, and immaculate skin luminance.',
    thumbnailGradient: 'from-zinc-900 via-rose-950 to-amber-200',
    tags: ['fashion', 'vogue', 'editorial', 'studio', 'glamour'],
    author: 'Chloe Dupont',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    downloadsCount: 16400,
    rating: 4.96,
    likesCount: 3890,
    isCommunity: true,
    recommendedFor: ['Fashion Runways', 'Studio Portraits', 'Model Portfolios'],
    settings: {
      exposure: 2,
      contrast: 32,
      highlights: -15,
      shadows: -8,
      whites: 16,
      blacks: -12,
      temperature: 4,
      tint: 6,
      saturation: -6,
      vibrance: 12,
      clarity: 18,
      sharpness: 34,
      vignette: -18,
      splitToning: {
        shadowHue: 280,
        shadowSat: 16,
        highlightHue: 35,
        highlightSat: 22,
        balance: 0,
      },
    },
  },
  {
    id: 'mkt-dark-nordic-forest',
    name: 'Nordic Dark Pine & Moss',
    category: 'Moody',
    description: 'Deep desaturated emerald tones, atmospheric fog lift, and dramatic shadow roll-off.',
    thumbnailGradient: 'from-emerald-950 via-teal-900 to-slate-800',
    tags: ['nature', 'forest', 'moody', 'nordic', 'landscape'],
    author: 'Lars Lindqvist',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    downloadsCount: 12700,
    rating: 4.89,
    likesCount: 2950,
    isCommunity: true,
    recommendedFor: ['Forest Landscapes', 'Overcast Days', 'Mountain Hikes'],
    settings: {
      exposure: -2,
      contrast: 24,
      highlights: -25,
      shadows: 8,
      whites: -10,
      blacks: 12,
      temperature: -8,
      tint: 12,
      saturation: -18,
      vibrance: 14,
      clarity: 24,
      dehaze: 16,
      sharpness: 28,
      vignette: -24,
      splitToning: {
        shadowHue: 165,
        shadowSat: 32,
        highlightHue: 205,
        highlightSat: 18,
        balance: -10,
      },
    },
  },
  {
    id: 'mkt-leica-monochrome-pro',
    name: 'Leica Monochrom Pro Silver',
    category: 'Black & white',
    description: 'Pure silver-halide tonal gradation with rich Zone System midtone separation.',
    thumbnailGradient: 'from-black via-zinc-600 to-slate-200',
    tags: ['monochrome', 'leica', 'bnw', 'street', 'fine-art'],
    author: 'Marcus Weber',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    downloadsCount: 24600,
    rating: 4.99,
    likesCount: 6100,
    isCommunity: true,
    recommendedFor: ['Street Photography', 'Fine Art Portraits', 'Architecture'],
    settings: {
      exposure: 2,
      contrast: 34,
      highlights: -14,
      shadows: 10,
      whites: 18,
      blacks: -18,
      saturation: -100,
      vibrance: -100,
      clarity: 26,
      sharpness: 32,
      filmGrain: 28,
      vignette: -16,
    },
  },
];

export function getPresetById(id: string | null | undefined, customPresets: FilterPreset[] = []): FilterPreset | undefined {
  if (!id) return undefined;
  return (
    customPresets.find((p) => p.id === id) ||
    MARKETPLACE_PRESETS.find((p) => p.id === id) ||
    FILTER_PRESETS.find((p) => p.id === id)
  );
}

export function getAllPresets(customPresets: FilterPreset[] = []): FilterPreset[] {
  return [...customPresets, ...MARKETPLACE_PRESETS, ...FILTER_PRESETS];
}

export function searchPresets(
  query: string,
  category: string = 'All',
  customPresets: FilterPreset[] = [],
  favoritesOnly: boolean = false,
  favoriteIds: string[] = []
): FilterPreset[] {
  const all = getAllPresets(customPresets);
  const q = query.trim().toLowerCase();

  return all.filter((p) => {
    if (favoritesOnly && !favoriteIds.includes(p.id)) return false;

    if (category !== 'All') {
      if (category === 'Custom' && !customPresets.some((cp) => cp.id === p.id)) {
        return false;
      }
      if (category === 'Marketplace' && !p.isCommunity) {
        return false;
      }
      if (category !== 'Custom' && category !== 'Marketplace' && p.category !== category) {
        return false;
      }
    }

    if (!q) return true;

    const nameMatch = p.name.toLowerCase().includes(q);
    const descMatch = p.description.toLowerCase().includes(q);
    const tagMatch = p.tags?.some((t) => t.toLowerCase().includes(q));
    const catMatch = p.category.toLowerCase().includes(q);
    const authorMatch = p.author?.toLowerCase().includes(q);

    return nameMatch || descMatch || tagMatch || catMatch || authorMatch;
  });
}

// ----------------------------------------------------------------------------
// Preset Import / Export / Sharing Utilities
// ----------------------------------------------------------------------------

/**
 * Generate a compact share code for a preset (base64 encoded JSON)
 */
export function generatePresetShareCode(preset: FilterPreset): string {
  const payload = {
    _app: 'lumina_preset_v1',
    name: preset.name,
    category: preset.category,
    description: preset.description,
    gradient: preset.thumbnailGradient,
    settings: preset.settings,
    hsl: preset.hsl,
    toneCurves: preset.toneCurves,
    tags: preset.tags,
    author: preset.author || 'Lumina Creator',
    created: Date.now(),
  };

  try {
    const jsonStr = JSON.stringify(payload);
    return `LUMINA_${btoa(unescape(encodeURIComponent(jsonStr)))}`;
  } catch (e) {
    return `LUMINA_${btoa(JSON.stringify(payload))}`;
  }
}

/**
 * Parse and validate a preset share code
 */
export function parsePresetShareCode(code: string): FilterPreset | null {
  try {
    let clean = code.trim();
    if (clean.startsWith('LUMINA_')) {
      clean = clean.replace('LUMINA_', '');
    }

    const jsonStr = decodeURIComponent(escape(atob(clean)));
    const parsed = JSON.parse(jsonStr);

    if (!parsed.name || !parsed.settings) {
      return null;
    }

    const preset: FilterPreset = {
      id: `imported_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
      name: parsed.name,
      category: parsed.category || 'Custom',
      description: parsed.description || 'Imported via share code',
      thumbnailGradient: parsed.gradient || 'from-indigo-600 to-purple-600',
      settings: parsed.settings || {},
      hsl: parsed.hsl,
      toneCurves: parsed.toneCurves,
      tags: parsed.tags || ['imported'],
      author: parsed.author,
      createdAt: parsed.created || Date.now(),
      shareCode: code,
    };

    return preset;
  } catch (err) {
    console.error('Failed to parse share code:', err);
    return null;
  }
}

/**
 * Export preset as JSON file download
 */
export function exportPresetAsJsonFile(preset: FilterPreset) {
  const data = JSON.stringify(preset, null, 2);
  const blob = new Blob([data], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${preset.name.replace(/[^a-zA-Z0-9_-]/g, '_')}_LuminaPreset.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export preset as Adobe Lightroom XMP format
 */
export function exportPresetAsXmp(preset: FilterPreset): string {
  const s = preset.settings;
  return `<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 7.0-c000">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:crs="http://ns.adobe.com/camera-raw-settings/1.0/"
    crs:PresetType="Normal"
    crs:Cluster=""
    crs:UUID="${preset.id}"
    crs:SupportsAmount="true"
    crs:ProcessVersion="15.4"
    crs:Exposure2012="${((s.exposure || 0) / 25).toFixed(2)}"
    crs:Contrast2012="${s.contrast || 0}"
    crs:Highlights2012="${s.highlights || 0}"
    crs:Shadows2012="${s.shadows || 0}"
    crs:Whites2012="${s.whites || 0}"
    crs:Blacks2012="${s.blacks || 0}"
    crs:Temperature="${s.temperature ? `+${s.temperature}` : '0'}"
    crs:Tint="${s.tint ? `+${s.tint}` : '0'}"
    crs:Saturation="${s.saturation || 0}"
    crs:Vibrance="${s.vibrance || 0}"
    crs:Clarity2012="${s.clarity || 0}"
    crs:Texture="${s.texture || 0}"
    crs:Dehaze="${s.dehaze || 0}"
    crs:GrainAmount="${s.filmGrain || 0}"
    crs:PostCropVignetteAmount="${s.vignette || 0}"
    crs:SplitToningShadowHue="${s.splitToning?.shadowHue || 0}"
    crs:SplitToningShadowSaturation="${s.splitToning?.shadowSat || 0}"
    crs:SplitToningHighlightHue="${s.splitToning?.highlightHue || 0}"
    crs:SplitToningHighlightSaturation="${s.splitToning?.highlightSat || 0}"
    crs:SplitToningBalance="${s.splitToning?.balance || 0}">
   <crs:Name>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">${preset.name}</rdf:li>
    </rdf:Alt>
   </crs:Name>
   <crs:Group>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Lumina Studio Presets</rdf:li>
    </rdf:Alt>
   </crs:Group>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>`;
}

/**
 * Download XMP preset file
 */
export function exportPresetAsXmpFile(preset: FilterPreset) {
  const xmp = exportPresetAsXmp(preset);
  const blob = new Blob([xmp], { type: 'application/xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${preset.name.replace(/[^a-zA-Z0-9_-]/g, '_')}.xmp`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
