import { FilterPreset } from '../types/editor';

export const FILTER_PRESETS: FilterPreset[] = [
  {
    id: 'portra-400',
    name: 'Kodak Portra 400',
    category: 'Film Emulation',
    description: 'Iconic warm skin tones, gentle highlight roll-off, and pastel greens.',
    thumbnailGradient: 'from-amber-200 via-orange-300 to-rose-300',
    settings: {
      exposure: 5,
      contrast: -8,
      highlights: -15,
      shadows: 18,
      temperature: 12,
      tint: 4,
      saturation: -5,
      vibrance: 14,
      clarity: 6,
      sharpness: 18,
      filmGrain: 22,
      filmGrainSize: 2,
      splitToning: {
        shadowHue: 215,
        shadowSat: 10,
        highlightHue: 42,
        highlightSat: 16,
        balance: 10,
      },
    },
    hsl: {
      red: { hue: 2, saturation: 10, luminance: 4 },
      orange: { hue: -3, saturation: 14, luminance: 8 },
      yellow: { hue: -6, saturation: -8, luminance: 2 },
      green: { hue: 15, saturation: -22, luminance: 6 },
      aqua: { hue: 8, saturation: -10, luminance: 0 },
      blue: { hue: -5, saturation: -14, luminance: 2 },
      purple: { hue: 0, saturation: 0, luminance: 0 },
      magenta: { hue: 0, saturation: 0, luminance: 0 },
    },
  },
  {
    id: 'fuji-pro-400h',
    name: 'Fuji Pro 400H',
    category: 'Film Emulation',
    description: 'Cool cyan shadows, airy luminous highlights, and minty greens.',
    thumbnailGradient: 'from-teal-200 via-emerald-200 to-cyan-300',
    settings: {
      exposure: 8,
      contrast: -12,
      highlights: -20,
      shadows: 22,
      whites: 10,
      temperature: -8,
      tint: -4,
      saturation: 8,
      vibrance: 20,
      clarity: 8,
      sharpness: 20,
      filmGrain: 18,
      filmGrainSize: 2,
      splitToning: {
        shadowHue: 175,
        shadowSat: 14,
        highlightHue: 55,
        highlightSat: 10,
        balance: -5,
      },
    },
  },
  {
    id: 'cinestill-800t',
    name: 'CineStill 800T',
    category: 'Film Emulation',
    description: 'Tungsten-balanced night cinematic look with signature warm halation.',
    thumbnailGradient: 'from-indigo-900 via-teal-700 to-orange-500',
    settings: {
      exposure: 6,
      contrast: 18,
      highlights: 12,
      shadows: 8,
      temperature: -18,
      tint: 10,
      saturation: 16,
      vibrance: 25,
      clarity: 15,
      sharpness: 22,
      vignette: -18,
      filmGrain: 35,
      filmGrainSize: 3,
      splitToning: {
        shadowHue: 200,
        shadowSat: 22,
        highlightHue: 25,
        highlightSat: 28,
        balance: 15,
      },
    },
  },
  {
    id: 'ilford-hp5',
    name: 'Ilford HP5 Plus',
    category: 'B&W',
    description: 'Classic monochrome with punchy midtones, rich silver grain, and wide latitude.',
    thumbnailGradient: 'from-zinc-900 via-zinc-600 to-zinc-200',
    settings: {
      exposure: 4,
      contrast: 26,
      highlights: -10,
      shadows: 14,
      whites: 18,
      blacks: -16,
      saturation: -100,
      vibrance: -100,
      clarity: 22,
      sharpness: 30,
      filmGrain: 45,
      filmGrainSize: 3,
      vignette: -14,
    },
  },
  {
    id: 'leica-monochrom',
    name: 'Leica Monochrom',
    category: 'B&W',
    description: 'Ultra-crisp, deep matte blacks and velvety micro-contrast tonal gradations.',
    thumbnailGradient: 'from-black via-neutral-700 to-white',
    settings: {
      exposure: 0,
      contrast: 34,
      highlights: 8,
      shadows: -12,
      whites: 22,
      blacks: -24,
      saturation: -100,
      vibrance: -100,
      clarity: 32,
      sharpness: 45,
      filmGrain: 12,
      filmGrainSize: 1,
    },
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    category: 'Cinematic',
    description: 'Electric cyan-teal shadows with glowing neon magenta and amber highlights.',
    thumbnailGradient: 'from-fuchsia-600 via-purple-700 to-cyan-400',
    settings: {
      exposure: 4,
      contrast: 28,
      highlights: 20,
      shadows: -15,
      temperature: -14,
      tint: 28,
      saturation: 32,
      vibrance: 40,
      clarity: 25,
      sharpness: 28,
      vignette: -25,
      splitToning: {
        shadowHue: 190,
        shadowSat: 45,
        highlightHue: 310,
        highlightSat: 40,
        balance: 0,
      },
    },
  },
  {
    id: 'golden-hour-glow',
    name: 'Golden Hour Glow',
    category: 'Landscape',
    description: 'Bathing the scene in warm honey sunlight with softened contrasts.',
    thumbnailGradient: 'from-amber-500 via-orange-400 to-yellow-200',
    settings: {
      exposure: 8,
      contrast: -6,
      highlights: -18,
      shadows: 24,
      whites: 12,
      temperature: 32,
      tint: 8,
      saturation: 14,
      vibrance: 28,
      clarity: 10,
      sharpness: 16,
      vignette: -12,
      splitToning: {
        shadowHue: 35,
        shadowSat: 25,
        highlightHue: 48,
        highlightSat: 35,
        balance: 20,
      },
    },
  },
  {
    id: 'teal-and-orange',
    name: 'Urban Teal & Orange',
    category: 'Cinematic',
    description: 'Hollywood blockbuster color grade separating skin tones from atmospheric backdrops.',
    thumbnailGradient: 'from-teal-600 via-cyan-700 to-amber-500',
    settings: {
      exposure: 2,
      contrast: 22,
      highlights: -10,
      shadows: 12,
      temperature: 6,
      tint: -2,
      saturation: 18,
      vibrance: 30,
      clarity: 18,
      sharpness: 24,
      vignette: -16,
      splitToning: {
        shadowHue: 195,
        shadowSat: 38,
        highlightHue: 34,
        highlightSat: 36,
        balance: 5,
      },
    },
  },
  {
    id: 'moody-forest',
    name: 'Moody Pine Forest',
    category: 'Landscape',
    description: 'Desaturated emerald greens with deep dark shadows and misty highlights.',
    thumbnailGradient: 'from-emerald-950 via-teal-900 to-stone-400',
    settings: {
      exposure: -4,
      contrast: 16,
      highlights: -24,
      shadows: -14,
      whites: -10,
      blacks: -18,
      temperature: -10,
      tint: -12,
      saturation: -18,
      vibrance: 12,
      clarity: 22,
      sharpness: 26,
      dehaze: 14,
      vignette: -30,
    },
  },
  {
    id: 'editorial-fashion',
    name: 'Editorial High Fashion',
    category: 'Portrait',
    description: 'Polished studio lighting look with smooth skin luminance and crisp details.',
    thumbnailGradient: 'from-rose-100 via-stone-200 to-neutral-800',
    settings: {
      exposure: 6,
      contrast: 14,
      highlights: -12,
      shadows: 16,
      whites: 14,
      blacks: -8,
      temperature: 4,
      tint: 6,
      saturation: -4,
      vibrance: 18,
      clarity: 14,
      sharpness: 35,
      filmGrain: 8,
    },
  },
  {
    id: 'vintage-polaroid',
    name: '1970s Polaroid',
    category: 'Vintage',
    description: 'Lifted matte faded blacks, nostalgic warm shift, and characteristic soft glow.',
    thumbnailGradient: 'from-yellow-100 via-amber-200 to-stone-400',
    settings: {
      exposure: 10,
      contrast: -22,
      highlights: -25,
      shadows: 35,
      whites: -14,
      blacks: 28, // lifted blacks
      temperature: 16,
      tint: 12,
      saturation: -12,
      vibrance: 8,
      clarity: -10,
      sharpness: 8,
      filmGrain: 40,
      filmGrainSize: 3,
      vignette: -20,
    },
  },
  {
    id: 'pastel-dream',
    name: 'Pastel Dreamscape',
    category: 'Creative',
    description: 'High key ethereal tones with candy pinks, soft baby blues, and luminous highlights.',
    thumbnailGradient: 'from-pink-300 via-purple-200 to-sky-300',
    settings: {
      exposure: 15,
      contrast: -18,
      highlights: -30,
      shadows: 40,
      whites: 20,
      temperature: 2,
      tint: 18,
      saturation: 12,
      vibrance: 35,
      clarity: -14,
      sharpness: 12,
      splitToning: {
        shadowHue: 260,
        shadowSat: 20,
        highlightHue: 330,
        highlightSat: 22,
        balance: 10,
      },
    },
  },
  {
    id: 'arctic-nordic',
    name: 'Nordic Glacier',
    category: 'Landscape',
    description: 'Crisp glacial blues, clean white peaks, and deep contrast.',
    thumbnailGradient: 'from-cyan-100 via-blue-200 to-slate-800',
    settings: {
      exposure: 6,
      contrast: 18,
      highlights: -16,
      shadows: 10,
      whites: 22,
      temperature: -24,
      tint: -6,
      saturation: -10,
      vibrance: 22,
      clarity: 26,
      sharpness: 32,
      dehaze: 18,
    },
  },
  {
    id: 'velvia-50',
    name: 'Fuji Velvia 50',
    category: 'Landscape',
    description: 'Ultra-vivid landscapes with hyper-saturated skies and intense botanical greens.',
    thumbnailGradient: 'from-emerald-500 via-amber-400 to-sky-600',
    settings: {
      exposure: 2,
      contrast: 24,
      highlights: 6,
      shadows: -10,
      whites: 16,
      blacks: -12,
      temperature: 8,
      tint: 4,
      saturation: 38,
      vibrance: 45,
      clarity: 20,
      sharpness: 28,
    },
  },
  {
    id: 'cinematic-matte',
    name: 'Dark Film Noir',
    category: 'Cinematic',
    description: 'Heavily stylized moody film look with muted colors and dramatic vignette.',
    thumbnailGradient: 'from-slate-950 via-zinc-800 to-stone-600',
    settings: {
      exposure: -8,
      contrast: 22,
      highlights: -20,
      shadows: -18,
      whites: -15,
      blacks: 15,
      temperature: -8,
      tint: -4,
      saturation: -28,
      vibrance: -10,
      clarity: 24,
      sharpness: 20,
      vignette: -45,
      filmGrain: 28,
      filmGrainSize: 2,
    },
  },
];
