import { ImageFile, RawMetadata } from '../types/editor';

export interface SampleImage {
  id: string;
  name: string;
  category: 'Landscape' | 'Portrait' | 'Night City' | 'Vintage' | 'Architecture' | 'RAW Sensor';
  url: string;
  width: number;
  height: number;
  format: string;
  description: string;
  isRaw?: boolean;
  rawMetadata?: Partial<RawMetadata>;
}

export const SAMPLE_IMAGES: SampleImage[] = [
  {
    id: 'sample-raw-sony-arw',
    name: 'Glacier_Fjord_DSC04921.ARW',
    category: 'RAW Sensor',
    url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=2400&q=95',
    width: 3840,
    height: 2560,
    format: 'arw',
    isRaw: true,
    description: '14-Bit Sony ARW RAW file with extreme highlight headroom, deep shadow dynamic range, and RGGB sensor array.',
    rawMetadata: {
      isRaw: true,
      cameraMake: 'Sony',
      cameraModel: 'Alpha 7R V (61.0 MP)',
      lens: 'FE 24-70mm F2.8 GM II',
      iso: 100,
      focalLength: '24mm',
      aperture: 'f/8.0',
      shutterSpeed: '1/320s',
      colorSpace: 'ProPhoto RGB / Wide Gamut',
      bitDepth: 14,
      bayerPattern: 'RGGB',
      wbKelvin: 5600,
      wbTint: 8,
      sensorDimensions: '35.7 x 23.8 mm (Exmor R BSI)',
      exposureBias: '-0.3 EV',
    },
  },
  {
    id: 'sample-raw-canon-cr3',
    name: 'Desert_Dunes_Sunset_IMG_8201.CR3',
    category: 'RAW Sensor',
    url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=2400&q=95',
    width: 3840,
    height: 2560,
    format: 'cr3',
    isRaw: true,
    description: 'Canon CR3 RAW sensor capture. Ideal for testing highlight recovery, warmth kelvin shifts, and Adobe / Camera profiles.',
    rawMetadata: {
      isRaw: true,
      cameraMake: 'Canon',
      cameraModel: 'EOS R5 Mark II (45.0 MP)',
      lens: 'RF 24-70mm F2.8 L IS USM',
      iso: 100,
      focalLength: '35mm',
      aperture: 'f/4.0',
      shutterSpeed: '1/500s',
      colorSpace: 'ProPhoto RGB',
      bitDepth: 14,
      bayerPattern: 'RGGB',
      wbKelvin: 5200,
      wbTint: 12,
      sensorDimensions: '36.0 x 24.0 mm Dual Pixel CMOS',
      exposureBias: '0.0 EV',
    },
  },
  {
    id: 'sample-raw-fuji-raf',
    name: 'Kyoto_Tea_House_DSCF1042.RAF',
    category: 'RAW Sensor',
    url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=2400&q=95',
    width: 3840,
    height: 2560,
    format: 'raf',
    isRaw: true,
    description: 'Fujifilm X-Trans 5 sensor RAW. Rich tonal roll-off, filmic texture, and chromatic aberration correction testing.',
    rawMetadata: {
      isRaw: true,
      cameraMake: 'Fujifilm',
      cameraModel: 'X-T5 (40.2 MP)',
      lens: 'XF 23mm F1.4 R LM WR',
      iso: 125,
      focalLength: '23mm (35mm Equiv)',
      aperture: 'f/2.0',
      shutterSpeed: '1/1000s',
      colorSpace: 'ProPhoto RGB',
      bitDepth: 14,
      bayerPattern: 'X-Trans',
      wbKelvin: 6100,
      wbTint: 15,
      sensorDimensions: '23.5 x 15.6 mm APS-C X-Trans',
      exposureBias: '+0.3 EV',
    },
  },
  {
    id: 'sample-landscape-dolomites',
    name: 'Alpine Sunrise Peaks.jpg',
    category: 'Landscape',
    url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=2400&q=90',
    width: 2400,
    height: 1600,
    format: 'jpeg',
    description: 'High dynamic range mountain sunset with vivid reflections and deep shadows.',
  },
  {
    id: 'sample-portrait-studio',
    name: 'Editorial Portrait.jpg',
    category: 'Portrait',
    url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=2400&q=90',
    width: 2400,
    height: 1600,
    format: 'jpeg',
    description: 'Natural light portrait ideal for AI skin retouching, color grading, and film simulation.',
  },
  {
    id: 'sample-night-tokyo',
    name: 'Cyberpunk Tokyo Rain.jpg',
    category: 'Night City',
    url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=2400&q=90',
    width: 2400,
    height: 1500,
    format: 'jpeg',
    description: 'Night neon reflections, wet pavement, and rich cyberpunk lighting atmosphere.',
  },
  {
    id: 'sample-vintage-car',
    name: 'Classic 1960s Roadster.jpg',
    category: 'Vintage',
    url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=2400&q=90',
    width: 2400,
    height: 1600,
    format: 'jpeg',
    description: 'Metallic reflections, chrome details, and vintage aesthetic curves.',
  },
  {
    id: 'sample-architecture-minimal',
    name: 'Minimal Concrete Pavilion.jpg',
    category: 'Architecture',
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2400&q=90',
    width: 2400,
    height: 1600,
    format: 'jpeg',
    description: 'Modern geometric architecture with soft diffused daylight and sharp angles.',
  },
  {
    id: 'sample-screenshot-mobile-app',
    name: 'Mobile App Screen - Finance Dashboard.png',
    category: 'Architecture',
    url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=90',
    width: 1200,
    height: 2400,
    format: 'png',
    description: 'Mobile App User Interface screenshot. Ideal for testing Screenshot Studio, realistic iPhone 16 Pro device frames, clean status bars, and 3D floating perspective.',
  },
];

export function createSampleImageFile(sample: SampleImage): ImageFile {
  const isRaw = sample.isRaw ?? false;
  return {
    id: `sample_${sample.id}_${Date.now()}`,
    name: sample.name,
    originalUrl: sample.url,
    width: sample.width,
    height: sample.height,
    format: sample.format,
    size: isRaw ? 42500000 : 2840000,
    rawMetadata: {
      isRaw,
      cameraMake: sample.rawMetadata?.cameraMake || (isRaw ? 'Sony' : 'Sony Corporation'),
      cameraModel: sample.rawMetadata?.cameraModel || (isRaw ? 'Alpha 7R V' : 'ILCE-7RM5'),
      cameraSerialNumber: '4829103',
      lens: sample.rawMetadata?.lens || 'FE 24-70mm F2.8 GM II',
      lensSerialNumber: '1904822',
      iso: sample.rawMetadata?.iso || 100,
      focalLength: sample.rawMetadata?.focalLength || '35mm',
      focalLength35mm: sample.rawMetadata?.focalLength || '35mm',
      aperture: sample.rawMetadata?.aperture || 'f/2.8',
      shutterSpeed: sample.rawMetadata?.shutterSpeed || '1/250s',
      colorSpace: sample.rawMetadata?.colorSpace || (isRaw ? 'ProPhoto RGB / Wide Gamut' : 'sRGB IEC61966-2.1'),
      bitDepth: sample.rawMetadata?.bitDepth || (isRaw ? 14 : 8),
      bayerPattern: sample.rawMetadata?.bayerPattern || (isRaw ? 'RGGB' : undefined),
      whiteBalance: isRaw ? 'As Shot (5600K)' : 'Daylight (5500K)',
      wbKelvin: sample.rawMetadata?.wbKelvin || 5500,
      wbTint: sample.rawMetadata?.wbTint || 10,
      sensorDimensions: sample.rawMetadata?.sensorDimensions || '35.9 x 24.0 mm Full-Frame',
      dateShot: 'Aug 19, 2026',
      timeShot: '14:28:10',
      exposureBias: sample.rawMetadata?.exposureBias || '0.0 EV',
      meteringMode: 'Multi-segment Pattern',
      flashFired: false,
      author: 'Lumina Master Photographer',
      copyright: `© 2026 Lumina Studio. All Rights Reserved.`,
      copyrightNotice: 'Commercial reproduction prohibited without license',
      rightsUsageTerms: 'Editorial & Commercial License',
      title: sample.name.replace(/\.[^/.]+$/, ''),
      caption: sample.description,
      keywords: ['Landscape', 'Pro Photography', 'HDR', 'Color Master'],
      rating: 5,
      software: 'Lumina RAW Engine v2.0',
      gps: {
        latitude: 35.6586,
        longitude: 139.7454,
        altitude: 45,
        city: 'Tokyo',
        country: 'Japan',
        locationName: 'Minato, Tokyo',
      },
      privacy: {
        stripGpsOnExport: false,
        stripAllMetadataOnExport: false,
        copyrightOnlyOnExport: false,
      },
    },
    createdAt: Date.now(),
  };
}
