import { ToolCategoryId, ToolDefinition, ToolEducationData } from '../types/navigation';

export interface CategoryInfo {
  id: ToolCategoryId;
  title: string;
  subtitle: string;
  badge: string;
  accentColor: string;
  accentBg: string;
  accentBorder: string;
  iconName: string;
  toolCount: number;
}

export const TOOL_CATEGORIES_CONFIG: Record<ToolCategoryId, Omit<CategoryInfo, 'toolCount'>> = {
  raw: {
    id: 'raw',
    title: 'RAW Optics & Sensor',
    subtitle: 'Bayer demosaicing, camera profiles, lens correction & sensor calibration',
    badge: '16-BIT RAW',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Camera',
  },
  color: {
    id: 'color',
    title: 'Color & Grading',
    subtitle: '8-Channel HSL, temperature, split-toning & 3D LUTs',
    badge: 'COLOR',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Palette',
  },
  light: {
    id: 'light',
    title: 'Light & Exposure',
    subtitle: 'Exposure, contrast, highlights, shadows & tone curves',
    badge: '32-BIT HDR',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Sun',
  },
  curves: {
    id: 'curves',
    title: 'Tone Curves',
    subtitle: 'RGB master, red, green, and blue parametric spline curves',
    badge: 'CURVES',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'TrendingUp',
  },
  hsl: {
    id: 'hsl',
    title: 'HSL & Selective Color',
    subtitle: 'Hue, saturation, and luminance across 8 independent color bands',
    badge: 'HSL',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Sliders',
  },
  masks: {
    id: 'masks',
    title: 'Masks & Selections',
    subtitle: 'Radial, linear gradient, luminance range, and AI subject masks',
    badge: 'MASKS',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Layers',
  },
  retouch: {
    id: 'retouch',
    title: 'Retouch & Repair',
    subtitle: 'Healing brush, clone stamp, patch, blemish eraser & frequency separation',
    badge: 'RETOUCH',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Wand2',
  },
  layers: {
    id: 'layers',
    title: 'Layers & Compositing',
    subtitle: 'Multi-track layers, blend modes, smart objects & layer masks',
    badge: 'LAYERS',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Layers',
  },
  design: {
    id: 'design',
    title: 'Design & Graphics',
    subtitle: 'Vector shapes, frames, borders, drawings, and stickers',
    badge: 'DESIGN',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Type',
  },
  typography: {
    id: 'typography',
    title: 'Typography & Text',
    subtitle: 'Rich fonts, letter spacing, curved paths, and text effects',
    badge: 'TYPE',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Type',
  },
  collage: {
    id: 'collage',
    title: 'Collage & Grid',
    subtitle: 'Dynamic grid layouts, aspect frames, borders & moodboards',
    badge: 'COLLAGE',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Grid',
  },
  ai: {
    id: 'ai',
    title: 'AI & Neural Studio',
    subtitle: 'Generative fill, object removal, neural relight, and depth mapping',
    badge: 'AI NEURAL',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Sparkles',
  },
  export: {
    id: 'export',
    title: 'Export & Mastering',
    subtitle: 'WebP, TIFF, PNG, AVIF, social media presets, watermark & metadata',
    badge: 'EXPORT',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Download',
  },
  utility: {
    id: 'utility',
    title: 'System & Diagnostics',
    subtitle: 'Performance monitor, GPU telemetry, plugin runner, and vault',
    badge: 'SYSTEM',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Zap',
  },
  basic: {
    id: 'basic',
    title: 'Basic & Geometry',
    subtitle: 'Crop, rotate, perspective, resize & framing',
    badge: 'CORE',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Crop',
  },
  detail: {
    id: 'detail',
    title: 'Detail & Clarity',
    subtitle: 'Sharpen, texture, clarity, dehaze & noise reduction',
    badge: 'OPTICAL',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Sliders',
  },
  portrait: {
    id: 'portrait',
    title: 'Portrait & Face',
    subtitle: 'Skin smoothing, face sculpting, eye enhancement & teeth whitening',
    badge: 'PORTRAIT',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'UserCheck',
  },
  effects: {
    id: 'effects',
    title: 'Effects & Cinema',
    subtitle: 'Film grain, vintage glow, glitch, chromatic aberration & flares',
    badge: 'EFFECTS',
    accentColor: 'text-zinc-200',
    accentBg: 'bg-zinc-900',
    accentBorder: 'border-zinc-800',
    iconName: 'Flame',
  },
};

export const MASTER_TOOLS_LIST: ToolDefinition[] = [
  // 1. BASIC
  {
    id: 'tool_crop',
    name: 'Lossless Crop',
    categoryId: 'basic',
    description: 'Crop freely or lock standard photographic aspect ratios (1:1, 16:9, 4:5, 9:16).',
    iconName: 'Crop',
    shortcut: 'C',
    targetTab: 'crop',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['crop', 'cut', 'aspect ratio', 'resize', 'frame', 'trim'],
    education: {
      whatItDoes: 'Trims image boundaries to improve visual composition and fit exact social or print formats.',
      whenToUse: 'Use early in your workflow to eliminate distracting background edges and emphasize the subject.',
      proTip: 'Enable Rule of Thirds or Golden Spiral overlays for cinematic balance.',
      sampleEffect: 'Reframes wide landscape into dramatic 16:9 cinematic vista.',
    },
  },
  {
    id: 'tool_rotate_straighten',
    name: 'Straighten & Rotate',
    categoryId: 'basic',
    description: 'Auto-level crooked horizons or rotate clockwise/counter-clockwise.',
    iconName: 'RotateCcw',
    targetTab: 'crop',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['rotate', 'straighten', 'level', 'horizon', 'angle', 'tilt'],
    education: {
      whatItDoes: 'Rotates the image with sub-degree accuracy to ensure horizons and vertical pillars are straight.',
      whenToUse: 'Whenever landscape horizons or architectural vertical lines are tilted.',
      proTip: 'Use the auto-straighten horizon detection for instant leveling.',
      sampleEffect: 'Fixes a 2.5° tilted ocean horizon with lossless canvas boundary fill.',
    },
  },
  {
    id: 'tool_perspective_keystone',
    name: 'Perspective Keystone',
    categoryId: 'basic',
    description: 'Correct vertical and horizontal converging architectural perspective.',
    iconName: 'Minimize2',
    isProOnly: true,
    targetTab: 'geometry',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['perspective', 'keystone', 'architecture', 'skew', 'vertical', 'horizontal'],
    education: {
      whatItDoes: 'Transforms the trapezoidal perspective grid to make converging building walls parallel.',
      whenToUse: 'When photographing buildings or tall objects from ground level looking up.',
      proTip: 'Apply Vertical keystone correction first before fine-tuning horizontal balance.',
      sampleEffect: 'Converts angled skyscraper photo into flat architectural elevation.',
    },
  },
  {
    id: 'tool_resize_resolution',
    name: 'Canvas Resize & Scale',
    categoryId: 'basic',
    description: 'Change pixel dimensions or physical print DPI without loss of quality.',
    iconName: 'Maximize2',
    targetTab: 'crop',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['resize', 'scale', 'dimensions', 'resolution', 'dpi', 'megapixels'],
    education: {
      whatItDoes: 'Resamples image raster dimensions using Bicubic or Lanczos-3 interpolation.',
      whenToUse: 'When preparing images for specific web constraints, banners, or 300 DPI print jobs.',
      proTip: 'Preserve aspect ratio lock to prevent stretching subjects.',
      sampleEffect: 'Downscales 48MP raw capture to lightweight 4K web asset.',
    },
  },

  // 2. LIGHT
  {
    id: 'tool_exposure',
    name: '32-Bit Exposure',
    categoryId: 'light',
    description: 'Linear sensor exposure adjustment across -5.0 to +5.0 EV stops.',
    iconName: 'Sun',
    shortcut: 'E',
    targetTab: 'adjust',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['exposure', 'brightness', 'light', 'dark', 'ev', 'stops', 'overexposed', 'underexposed'],
    education: {
      whatItDoes: 'Multiplies linear RGB photon values uniformly to simulate camera aperture/shutter changes.',
      whenToUse: 'First global step when an image is overall too dark or washed out.',
      proTip: 'Watch the real-time histogram to avoid clipping pure whites (255) or crushed blacks (0).',
      sampleEffect: 'Recovers 1.5 stops of underexposed shadow detail on portrait subject.',
    },
  },
  {
    id: 'tool_contrast',
    name: 'Contrast & Tone Curve',
    categoryId: 'light',
    description: 'Expands the tonal difference between bright highlights and deep shadows.',
    iconName: 'CircleDot',
    targetTab: 'adjust',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['contrast', 'pop', 'punch', 'dynamic range', 'flat', 'tonal'],
    education: {
      whatItDoes: 'Applies an S-curve to midtones, deepening shadows and brightening highlights.',
      whenToUse: 'To add depth and punch to flat, hazy, or low-contrast RAW files.',
      proTip: 'Combine moderate contrast with Clarity for modern commercial punch without harsh clipping.',
      sampleEffect: 'Transforms flat cloudy scene into rich, punchy commercial shot.',
    },
  },
  {
    id: 'tool_highlights_shadows',
    name: 'Highlights & Shadows Recovery',
    categoryId: 'light',
    description: 'Targeted recovery of blown-out skies and crushed shadow regions.',
    iconName: 'Sliders',
    targetTab: 'adjust',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['highlights', 'shadows', 'recovery', 'sky', 'clouds', 'dark areas', 'blown out'],
    education: {
      whatItDoes: 'Selectively compresses high-luminance zones or elevates dark zones without affecting midtones.',
      whenToUse: 'High dynamic range scenes with bright sunny skies and dark foreground shadows.',
      proTip: 'Pull highlights to -40 and push shadows to +25 for an instant HDR balance.',
      sampleEffect: 'Brings back sunset cloud colors while revealing foreground foliage.',
    },
  },
  {
    id: 'tool_spline_curves',
    name: 'RGB & Tonal Spline Curves',
    categoryId: 'light',
    description: 'Master luminance and individual Red, Green, Blue spline tone curves.',
    iconName: 'TrendingUp',
    isProOnly: true,
    targetTab: 'curves',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['curves', 'spline', 'tone curve', 'rgb curves', 'matte black', 'crush'],
    education: {
      whatItDoes: 'Provides granular control over the transfer function mapping input values to output tones.',
      whenToUse: 'Advanced colorists who want filmic matte blacks, custom cross-processing, or split contrast.',
      proTip: 'Raise the bottom-left point slightly off 0 to create vintage matte-black film tones.',
      sampleEffect: 'Custom S-curve gives rich Kodachrome shadow roll-off.',
    },
  },

  // 3. COLOR
  {
    id: 'tool_white_balance',
    name: 'White Balance & Kelvin',
    categoryId: 'color',
    description: 'Calibrated color temperature (2000K–12000K) and green/magenta tint.',
    iconName: 'Thermometer',
    shortcut: 'W',
    targetTab: 'adjust',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['white balance', 'kelvin', 'temperature', 'tint', 'warm', 'cool', 'yellow', 'blue', 'orange'],
    education: {
      whatItDoes: 'Neutralizes color casts caused by ambient lighting (tungsten, fluorescent, golden hour).',
      whenToUse: 'To correct yellow indoor lighting or add warm golden-hour sunset vibes.',
      proTip: 'Use the eyedropper on a known neutral grey or white surface in your photo.',
      sampleEffect: 'Warms a cool 6500K overcast portrait to inviting 5200K golden sunlight.',
    },
  },
  {
    id: 'tool_hsl_mixer',
    name: '8-Channel HSL Color Mixer',
    categoryId: 'color',
    description: 'Individual Hue, Saturation, and Luminance for Red, Orange, Yellow, Green, Aqua, Blue, Purple, Magenta.',
    iconName: 'Palette',
    isProOnly: true,
    targetTab: 'hsl',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['hsl', 'color mixer', 'hue', 'saturation', 'luminance', 'orange skin', 'blue sky', 'green foliage'],
    education: {
      whatItDoes: 'Allows precision alteration of individual color vectors without shifting other hues.',
      whenToUse: 'To darken blue skies (Blue Luminance), brighten skin tones (Orange Luminance), or desaturate distracting colors.',
      proTip: 'Boost Orange Luminance (+15) and drop Orange Saturation (-5) for glowing, clean portraits.',
      sampleEffect: 'Turns dull green forest into deep emerald foliage and makes blue sky cobalt.',
    },
  },
  {
    id: 'tool_color_grading_wheels',
    name: '3-Way Color Grading Wheels',
    categoryId: 'color',
    description: 'Industry standard Lift / Gamma / Gain color wheels for Shadows, Midtones, Highlights.',
    iconName: 'Disc',
    isProOnly: true,
    targetTab: 'colorgrading',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['color grading', 'color wheels', 'lift', 'gamma', 'gain', 'split toning', 'teal orange', 'cinematic color'],
    education: {
      whatItDoes: 'Injects specific color hues and saturation into darks, midtones, and bright highlights independently.',
      whenToUse: 'Creating signature cinematic looks like Hollywood Teal & Orange or Cyberpunk Violet.',
      proTip: 'Push Shadows toward cyan-teal (200°) and Highlights toward warm amber-gold (35°).',
      sampleEffect: 'Instantly gives footage a dramatic David Fincher or Blade Runner film aesthetic.',
    },
  },
  {
    id: 'tool_3d_luts',
    name: '3D LUT & Film Simulations',
    categoryId: 'color',
    description: 'Apply .CUBE 3D lookup tables, Fujifilm simulations, and Kodak/Polaroid film emulations.',
    iconName: 'Film',
    targetTab: 'filmsim',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['lut', 'film simulation', 'fujifilm', 'kodak', 'portra', 'cinestill', 'polaroid', 'cinema'],
    education: {
      whatItDoes: 'Re-maps entire 3D RGB color cubes to match specific analog film chemistries.',
      whenToUse: 'When you want instant authentic photographic film character with custom intensity mixing.',
      proTip: 'Use Portra 400 for flattering skin tones or CineStill 800T for neon nighttime street photography.',
      sampleEffect: 'Emulates Kodak Portra 400 with soft pastel tones and natural highlight roll-off.',
    },
  },

  // 4. DETAIL
  {
    id: 'tool_sharpening',
    name: 'High-Pass Texture Sharpening',
    categoryId: 'detail',
    description: 'Multi-radius unsharp masking with edge masking to prevent grain amplification.',
    iconName: 'Zap',
    targetTab: 'detail',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['sharpen', 'crisp', 'focus', 'details', 'unsharp mask', 'edge'],
    education: {
      whatItDoes: 'Increases micro-contrast along detected high-frequency pixel edges.',
      whenToUse: 'Final step to restore optical crispness after resizing or lens softening.',
      proTip: 'Hold the Masking slider to protect smooth skin and sky from unwanted noise sharpening.',
      sampleEffect: 'Brings out crisp eyelashes, fabric textures, and architectural masonry.',
    },
  },
  {
    id: 'tool_noise_reduction',
    name: 'Luminance & Chrominance Denoise',
    categoryId: 'detail',
    description: 'Dual-pass bilateral filter suppressing color speckling and luminance grain.',
    iconName: 'Shield',
    targetTab: 'detail',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['noise', 'denoise', 'grain', 'speckles', 'high iso', 'clean', 'low light'],
    education: {
      whatItDoes: 'Blurs random high-ISO grain and chromatic color blotches while preserving subject edges.',
      whenToUse: 'Nighttime, concert, or indoor photos shot at high ISO (3200+).',
      proTip: 'Increase Color Noise Reduction first (kills ugly magenta/green speckles) before Luminance.',
      sampleEffect: 'Cleans up noisy ISO 6400 concert photo without turning faces to plastic.',
    },
  },
  {
    id: 'tool_clarity_texture',
    name: 'Clarity & Dehaze',
    categoryId: 'detail',
    description: 'Midtone micro-contrast enhancement and atmospheric fog/haze removal.',
    iconName: 'CloudRain',
    targetTab: 'adjust',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['clarity', 'dehaze', 'texture', 'fog', 'smog', 'haze', 'punch', 'clouds'],
    education: {
      whatItDoes: 'Boosts contrast strictly in local midtone gradients and cuts through atmospheric scattering.',
      whenToUse: 'Mountain landscapes with distant fog, or to give gritty textured portraits more punch.',
      proTip: 'Use negative Clarity (-10) as an ultra-subtle skin softening glamour glow.',
      sampleEffect: 'Cuts through foggy mountain valley to reveal sharp ridges and trees.',
    },
  },

  // 5. AI STUDIO
  {
    id: 'tool_ai_generative_fill',
    name: 'Generative Fill & Expand',
    categoryId: 'ai',
    description: 'Add new elements or expand canvas borders seamlessly using generative diffusion.',
    iconName: 'Sparkles',
    isAiPowered: true,
    engineType: 'AI',
    isOfflineCapable: false,
    requiresCloudAi: true,
    privacyNotice: 'Transfers cropped target patch to generative diffusion servers.',
    targetTab: 'ai',
    keywords: ['generative fill', 'ai fill', 'expand canvas', 'outpaint', 'generate', 'add object', 'prompt'],
    education: {
      whatItDoes: 'Synthesizes context-aware photographic pixels matching the lighting, texture, and grain of your scene.',
      whenToUse: 'To un-crop a tight photo, add complementary elements, or transform empty spaces.',
      proTip: 'Leave prompt empty for seamless background extension, or describe exact additions.',
      sampleEffect: 'Expands a vertical photo into an ultrawide cinematic 21:9 banner.',
    },
  },
  {
    id: 'tool_ai_object_removal',
    name: 'Object Removal (Telea + AI)',
    categoryId: 'ai',
    description: 'Local Telea Fast Inpainting with optional generative diffusion object removal.',
    iconName: 'Eraser',
    isAiPowered: true,
    engineType: 'HYBRID',
    isOfflineCapable: true,
    shortcut: 'O',
    targetTab: 'ai',
    keywords: ['remove object', 'erase person', 'photobomb', 'inpaint', 'clean background', 'magic eraser', 'trash'],
    education: {
      whatItDoes: 'Reconstructs background texture locally using Fast Telea or optional Cloud Generative Diffusion.',
      whenToUse: 'Removing tourists from travel photos, cleaning up power lines, or eliminating sensor dust spots.',
      proTip: 'Brush slightly outside the object boundary for seamless blending.',
      sampleEffect: 'Erases crowded tourists in front of the Eiffel Tower leaving a pristine empty plaza.',
    },
  },
  {
    id: 'tool_ai_background_studio',
    name: 'Background Studio & Bokeh',
    categoryId: 'ai',
    description: 'Subject isolation with optical depth bokeh blur or background replacement.',
    iconName: 'Image',
    isAiPowered: true,
    engineType: 'HYBRID',
    isOfflineCapable: true,
    targetTab: 'ai',
    keywords: ['background', 'remove background', 'replace background', 'transparent', 'bokeh', 'portrait mode', 'studio'],
    education: {
      whatItDoes: 'Segments foreground subject and applies optical lens depth defocus or background swap.',
      whenToUse: 'Product photography, e-commerce headshots, or turning messy rooms into luxury studios.',
      proTip: 'Enable "Harmonize Light" to automatically adapt subject color temperature to the new background.',
      sampleEffect: 'Transports indoor casual selfie into a rooftop sunset cocktail bar with natural rim light.',
    },
  },
  {
    id: 'tool_ai_relight',
    name: 'AI 3D Relighting & Light Studio',
    categoryId: 'ai',
    description: 'Position virtual 3D point lights, spotlights, and rim lights around your subject.',
    iconName: 'Sun',
    isAiPowered: true,
    engineType: 'AI',
    isOfflineCapable: false,
    requiresCloudAi: true,
    isProOnly: true,
    targetTab: 'lighting',
    keywords: ['relight', '3d lighting', 'rim light', 'studio light', 'softbox', 'spotlight', 'lighting angle'],
    education: {
      whatItDoes: 'Estimates 3D normal vectors of the subject and renders synthetic photographic light sources.',
      whenToUse: 'Adding dramatic rim lights to portraits, fixing flat overcast lighting, or matching studio setups.',
      proTip: 'Add an amber Key Light from the right and a cyan Rim Light from behind for high-end fashion depth.',
      sampleEffect: 'Adds vibrant neon cyan rim lighting behind a musician portrait.',
    },
  },
  {
    id: 'tool_ai_creative_director',
    name: 'AI Creative Director (Groq / BYOK)',
    categoryId: 'ai',
    description: 'Chat with Groq LPU reasoning engine to describe any mood, style, or complex edit.',
    iconName: 'BrainCircuit',
    isAiPowered: true,
    engineType: 'AI',
    isOfflineCapable: false,
    requiresCloudAi: true,
    shortcut: 'Ctrl+Space',
    targetTab: 'nlp',
    keywords: ['ai assistant', 'creative director', 'groq', 'chat edit', 'natural language', 'prompt', 'smart edit'],
    education: {
      whatItDoes: 'Decomposes your conversational intent into a structured 12-step non-destructive editing plan.',
      whenToUse: 'When you have a vision ("make this look like Vogue 1990s") but do not know which sliders to move.',
      proTip: 'Review the generated step-by-step plan before clicking Apply to learn professional grading recipes.',
      sampleEffect: 'Turns "make this moody Scandinavian film" into 14 precise curve and HSL adjustments in 40ms.',
    },
  },

  // 6. PORTRAIT
  {
    id: 'tool_skin_smoothing',
    name: 'Skin Smoothing & Retouch',
    categoryId: 'portrait',
    description: 'Bilateral texture smoothing preserving natural skin pores and sharpness.',
    iconName: 'Sparkles',
    targetTab: 'portrait',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['skin', 'smooth', 'skin retouch', 'pores', 'blemish', 'face', 'flawless', 'beauty'],
    education: {
      whatItDoes: 'Applies frequency separation separating skin color blotches from pore texture high frequencies.',
      whenToUse: 'Portrait and fashion photography to create smooth, magazine-quality skin without plastic blur.',
      proTip: 'Keep Texture Slider at 60%+ so natural pores remain crisp and authentic.',
      sampleEffect: 'Smoothes uneven skin tones and shines while keeping razor-sharp eye and pore detail.',
    },
  },
  {
    id: 'tool_face_sculpt_eyes',
    name: 'Face Sculpt, Eyes & Smile',
    categoryId: 'portrait',
    description: 'Catchlight brightening, iris saturation boost, teeth whitening, and jawline contouring.',
    iconName: 'Eye',
    targetTab: 'portrait',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['eyes', 'iris', 'teeth', 'smile', 'jawline', 'face sculpt', 'catchlight', 'portrait retouch'],
    education: {
      whatItDoes: 'Identifies facial regions to enhance irises, sclera, teeth, and contour lines.',
      whenToUse: 'Making portrait subjects look vibrant, rested, and naturally confident.',
      proTip: 'A subtle +15% Eye Brighten and +10% Teeth Whiten makes a huge subconscious impact.',
      sampleEffect: 'Makes eyes sparkle with vivid iris reflections and natural white smile.',
    },
  },

  // 7. RETOUCH
  {
    id: 'tool_healing_clone',
    name: 'Healing Brush & Clone Stamp',
    categoryId: 'retouch',
    description: 'Pixel-perfect texture cloning with automatic Poisson gradient blending.',
    iconName: 'Wand2',
    shortcut: 'S',
    targetTab: 'retouch',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['clone', 'stamp', 'heal', 'brush', 'retouch', 'blemish', 'dust spot', 'scratch'],
    education: {
      whatItDoes: 'Samples source texture and seamlessly blends it into destination pixels matching tone and grain.',
      whenToUse: 'Removing sensor dust specks, stray hairs, wrinkles, or background distractions.',
      proTip: 'Use a soft feather (40%) and sample clean skin nearby for invisible blending.',
      sampleEffect: 'Removes stray windblown hair crossing over subject’s forehead.',
    },
  },
  {
    id: 'tool_patch_blemish',
    name: 'Precision Patch & Blemish Eraser',
    categoryId: 'retouch',
    description: 'Lasso around large imperfections and drag to a clean reference texture patch.',
    iconName: 'Bandage',
    targetTab: 'retouch',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['patch', 'lasso heal', 'blemish remover', 'acne', 'spot heal'],
    education: {
      whatItDoes: 'Calculates seamless Poisson boundary equations across freeform lassoed selections.',
      whenToUse: 'Quickly clearing acne spots, water drops on lenses, or fabric stains.',
      proTip: 'Circle the blemish closely to minimize surrounding texture mismatch.',
      sampleEffect: 'Cleans up temporary skin redness and lens flare spots in seconds.',
    },
  },

  // 8. LAYERS
  {
    id: 'tool_layers_stack',
    name: 'Multi-Track Layer Stack',
    categoryId: 'layers',
    description: 'Non-destructive image layers, adjustment layers, text layers, and smart group folders.',
    iconName: 'Layers',
    shortcut: 'L',
    isProOnly: true,
    targetTab: 'layers',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['layers', 'stack', 'adjustment layer', 'group', 'opacity', 'visibility', 'lock'],
    education: {
      whatItDoes: 'Stacks multiple visual elements vertically with independent opacity and transform coordinates.',
      whenToUse: 'Compositing graphic design banners, photo collages, or multi-exposure blends.',
      proTip: 'Group related text and graphics layers into folders to keep complex projects organized.',
      sampleEffect: 'Combines portrait layer, text title layer, and smoke overlay layer into movie poster.',
    },
  },
  {
    id: 'tool_blend_modes',
    name: '16 Standard Blend Modes & Alpha Lock',
    categoryId: 'layers',
    description: 'Screen, Multiply, Overlay, Soft Light, Color Dodge, Luminosity, and difference modes.',
    iconName: 'Sparkle',
    isProOnly: true,
    targetTab: 'layers',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['blend mode', 'screen', 'multiply', 'overlay', 'color dodge', 'soft light', 'compositing'],
    education: {
      whatItDoes: 'Controls how color pixels on one layer interact mathematically with underlying layers.',
      whenToUse: 'Screen for light leaks and lens flares; Multiply for shadows and textures; Overlay for contrast.',
      proTip: 'Set a gold dust texture layer to "Color Dodge" with 60% opacity for magical glows.',
      sampleEffect: 'Blends optical lens flare overlay seamlessly into sunset photograph.',
    },
  },
  {
    id: 'tool_masks_selective',
    name: 'Selective Brush & Gradient Masks',
    categoryId: 'layers',
    description: 'Radial, Linear, Brush, Color Range, and Luminance Range precision masks.',
    iconName: 'SquareDashed',
    shortcut: 'M',
    isProOnly: true,
    targetTab: 'masks',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['mask', 'selective', 'radial mask', 'linear gradient', 'brush mask', 'subject mask', 'sky mask'],
    education: {
      whatItDoes: 'Restricts adjustments (exposure, curves, color) exclusively to targeted regions of the photo.',
      whenToUse: 'Brightening only the subject while darkening the background; color grading the sky independently.',
      proTip: 'Combine Radial Mask with Invert to create an instant background-only adjustment layer.',
      sampleEffect: 'Darkens surrounding room by -1 EV while maintaining crisp key light on the model.',
    },
  },

  // 9. EFFECTS
  {
    id: 'tool_film_grain',
    name: 'Analog Organic Film Grain',
    categoryId: 'effects',
    description: 'Physical 35mm and 120 medium format silver-halide grain synthesis.',
    iconName: 'Flame',
    targetTab: 'effects',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['film grain', 'grain', 'analog', 'vintage', '35mm', '120mm', 'texture'],
    education: {
      whatItDoes: 'Simulates organic silver-halide particle distribution with highlight and shadow response.',
      whenToUse: 'To add vintage warmth, analog character, or mask digital sensor sharpness.',
      proTip: 'Add 15% grain to eliminate digital color banding in smooth sky gradients.',
      sampleEffect: 'Gives digital mirrorless photo the organic grit of Kodak Tri-X 400 black & white.',
    },
  },
  {
    id: 'tool_vignette_bloom',
    name: 'Optic Vignette & Cinema Bloom',
    categoryId: 'effects',
    description: 'Customizable lens light falloff, corner feathering, and ethereal highlight bloom.',
    iconName: 'Circle',
    targetTab: 'effects',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['vignette', 'bloom', 'glow', 'halation', 'corner shadow', 'dreamy'],
    education: {
      whatItDoes: 'Darkens outer corners to draw the viewer’s eye inward and creates soft glow around light sources.',
      whenToUse: 'Portraits and cinematic stills to frame the subject and create dreamy romantic atmosphere.',
      proTip: 'Use a subtle Highlight Bloom (+20) with negative Vignette (-15) for vintage cinema vibes.',
      sampleEffect: 'Subtly frames the couple in a wedding portrait while making candles softly glow.',
    },
  },

  // 10. DESIGN
  {
    id: 'tool_typography_text',
    name: 'Typography & Text Studio',
    categoryId: 'design',
    description: '50+ curated font pairings, 3D shadows, curved text paths, letter spacing, and gradient fills.',
    iconName: 'Type',
    shortcut: 'T',
    targetTab: 'typography',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['text', 'typography', 'font', 'title', 'quote', 'caption', 'heading', 'poster text'],
    education: {
      whatItDoes: 'Adds vector text overlays with full kerning, line height, bevels, and drop shadow styling.',
      whenToUse: 'Creating magazine covers, YouTube thumbnails, album art, or social media quote cards.',
      proTip: 'Use uppercase Bold Serif with +4px Letter Spacing for high-fashion editorial aesthetics.',
      sampleEffect: 'Creates editorial "VOGUE" style typography header across top of portrait.',
    },
  },
  {
    id: 'tool_shapes_stickers',
    name: 'Shapes, Badges & Stickers',
    categoryId: 'design',
    description: 'Geometric vector shapes, decorative badges, social icons, frames, and custom stickers.',
    iconName: 'Shapes',
    targetTab: 'graphics',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['shapes', 'stickers', 'badges', 'arrows', 'frames', 'icons', 'graphics', 'branding'],
    education: {
      whatItDoes: 'Renders scalable vector elements with fill, stroke, drop shadows, and opacity control.',
      whenToUse: 'Designing promotional flyers, YouTube callout arrows, discount badges, and sale banners.',
      proTip: 'Add a subtle drop shadow to badges so they pop off busy photographic backgrounds.',
      sampleEffect: 'Adds "NEW ARRIVAL" badge and stylized geometric border frame.',
    },
  },
  {
    id: 'tool_vector_drawing',
    name: 'Vector Drawing & Brush Pen',
    categoryId: 'design',
    description: 'Pressure-sensitive drawing brushes, neon glow pens, highlighter markers, and vector strokes.',
    iconName: 'PenTool',
    shortcut: 'B',
    targetTab: 'drawing',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['drawing', 'brush', 'pen', 'neon pen', 'doodle', 'annotate', 'signature', 'marker'],
    education: {
      whatItDoes: 'Records smooth Bézier vector brush paths with adjustable smoothing and neon glow shaders.',
      whenToUse: 'Handwritten artist signatures, neon light doodles, photo annotations, or markup.',
      proTip: 'Use the Neon Glow brush to draw glowing light streaks around subjects.',
      sampleEffect: 'Draws vibrant neon angel wings and halos interacting with subject’s silhouette.',
    },
  },

  // 11. COLLAGE
  {
    id: 'tool_grid_collage',
    name: 'Smart Collage & Grid Studio',
    categoryId: 'collage',
    description: '100+ dynamic photo grid layouts with rounded corners, custom gutters, and background colors.',
    iconName: 'Grid',
    targetTab: 'collage',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['collage', 'grid', 'photo grid', 'split photo', 'moodboard', 'side by side', 'gallery wall'],
    education: {
      whatItDoes: 'Arranges multiple photos into proportional grid cells with individual zoom and pan control.',
      whenToUse: 'Creating Instagram carousel slides, multi-outfit lookbooks, event summaries, or moodboards.',
      proTip: 'Set border radius to 16px and gutter to 8px with a pastel background for modern editorial grids.',
      sampleEffect: 'Arranges 4 vacation moments into an elegant balanced magazine moodboard.',
    },
  },

  // 12. RAW
  {
    id: 'tool_raw_demosaic',
    name: 'Bayer Demosaicing & Sensor Profiles',
    categoryId: 'raw',
    description: 'AHD / VNG high-bit-depth demosaicing for Sony ARW, Canon CR3, Nikon NEF, Fuji RAF, and DNG.',
    iconName: 'Cpu',
    isProOnly: true,
    targetTab: 'rawoptics',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['raw', 'demosaic', 'bayer', 'x-trans', 'sensor', 'dng', 'arw', 'cr3', 'nef', '16-bit'],
    education: {
      whatItDoes: 'Reconstructs full RGB color pixels from raw sensor photodiode mosaic data with zero compression.',
      whenToUse: 'Developing uncompressed camera sensor files for maximum highlight and color recovery.',
      proTip: 'Use AHD demosaicing for razor-sharp landscape textures and VNG for smooth portrait gradients.',
      sampleEffect: 'Extracts 14.5 stops of dynamic range from Sony Alpha raw sensor file.',
    },
  },
  {
    id: 'tool_lens_correction',
    name: 'Lens Distortion & Vignette Calibration',
    categoryId: 'raw',
    description: 'Profile-based correction for barrel/pincushion distortion and chromatic purple/green fringing.',
    iconName: 'CircleDot',
    isProOnly: true,
    targetTab: 'rawoptics',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['lens correction', 'distortion', 'chromatic aberration', 'purple fringing', 'barrel', 'pincushion'],
    education: {
      whatItDoes: 'Applies optical inverse polynomial geometry to straighten curved ultra-wide lens lines and remove color halos.',
      whenToUse: 'Photos shot with wide-angle (16-35mm) or fast prime lenses (f/1.4) against bright backlit skies.',
      proTip: 'Defringe automatically eliminates purple edges on backlit hair and tree branches.',
      sampleEffect: 'Straightens wide-angle architectural curvature and removes purple fringing from branches.',
    },
  },

  // 13. EXPORT
  {
    id: 'tool_export_multi_format',
    name: 'High-Res Multi-Format Export',
    categoryId: 'export',
    description: 'Full-resolution rendering to WebP, 16-bit TIFF, JPEG, PNG, and AVIF with ProPhoto RGB color profiles.',
    iconName: 'Download',
    shortcut: 'Ctrl+E',
    targetAction: 'open_export',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['export', 'save', 'download', 'jpeg', 'png', 'webp', 'tiff', 'avif', 'full resolution', 'quality'],
    education: {
      whatItDoes: 'Compiles the full 32-bit floating point WebGL render graph into your chosen target file format.',
      whenToUse: 'When your edit is complete and ready for web publishing, printing, or client delivery.',
      proTip: 'Use 16-bit TIFF for fine-art printing and 92% WebP for lightning-fast web delivery.',
      sampleEffect: 'Renders crystal-clear 4K export with embedded sRGB ICC profile and zero color banding.',
    },
  },
  {
    id: 'tool_social_export',
    name: 'Social Media Presets & Stories',
    categoryId: 'export',
    description: 'Instant 1-click sizing for Instagram Post (4:5), Story/Reel (9:16), YouTube Thumbnail (16:9), and TikTok.',
    iconName: 'Share2',
    targetAction: 'open_social_export',
    engineType: 'LOCAL',
    isOfflineCapable: true,
    keywords: ['social media', 'instagram', 'story', 'reel', 'tiktok', 'youtube thumbnail', 'twitter', 'linkedin', 'facebook'],
    education: {
      whatItDoes: 'Auto-pads or crops your artwork to fit exact aspect ratios required by social platforms without quality loss.',
      whenToUse: 'Publishing to Instagram, TikTok, LinkedIn, or creating YouTube video thumbnails.',
      proTip: 'Instagram 4:5 (1080x1350) takes up the most screen real estate in mobile feeds.',
      sampleEffect: 'Formats landscape photo into flawless 9:16 vertical story with blurred background frame.',
    },
  },
];

export function getToolsByCategory(categoryId: ToolCategoryId): ToolDefinition[] {
  return MASTER_TOOLS_LIST.filter((t) => t.categoryId === categoryId);
}

export function searchTools(query: string, mode: 'beginner' | 'pro' = 'pro'): ToolDefinition[] {
  if (!query.trim()) {
    return mode === 'beginner' ? MASTER_TOOLS_LIST.filter((t) => !t.isProOnly) : MASTER_TOOLS_LIST;
  }
  const q = query.toLowerCase().trim();
  return MASTER_TOOLS_LIST.filter((tool) => {
    if (mode === 'beginner' && tool.isProOnly) return false;
    return (
      tool.name.toLowerCase().includes(q) ||
      tool.description.toLowerCase().includes(q) ||
      tool.keywords.some((k) => k.toLowerCase().includes(q)) ||
      tool.categoryId.toLowerCase().includes(q)
    );
  });
}
