/**
 * Lumina Studio Pro — Universal AI Provider Presets & Capability Registry
 * Contains strict provider definitions, endpoint contracts, capabilities, and data retention policies.
 */

import { AIProviderPreset, AICapabilities } from '../../types/aiProviderGateway';

export const AI_PROVIDER_PRESETS: Record<string, AIProviderPreset> = {
  openai: {
    id: 'openai',
    name: 'OpenAI',
    type: 'cloud',
    defaultEndpoint: 'https://api.openai.com/v1',
    authType: 'bearer',
    requestFormat: 'openai_chat_completions',
    responseFormat: 'openai_standard',
    browserDirectSupported: true, // OpenAI supports direct browser Authorization: Bearer calls
    documentationUrl: 'https://platform.openai.com/docs/api-reference',
    keyPlaceholder: 'sk-proj-...',
    dataRetentionPolicy: 'zero_retention_api',
    capabilities: {
      textInput: true,
      textOutput: true,
      imageInput: true,
      imageOutput: true, // DALL-E 3
      imageEditing: true, // Inpainting via images/edits
      streamingSupport: true,
      embeddings: true,
      toolCalling: true,
    },
    defaultModels: [
      {
        id: 'gpt-4o',
        name: 'GPT-4o (Omni Multimodal Vision)',
        contextWindow: 128000,
        maxOutputTokens: 4096,
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.005, completionPer1k: 0.015, imageAnalysisUSD: 0.00765 },
        isDefault: true,
        recommendedFor: ['scene_analysis', 'natural_language_editing', 'metadata_generation'],
      },
      {
        id: 'gpt-4o-mini',
        name: 'GPT-4o Mini (Fast & Cost-Efficient)',
        contextWindow: 128000,
        maxOutputTokens: 4096,
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.00015, completionPer1k: 0.0006, imageAnalysisUSD: 0.001 },
        recommendedFor: ['natural_language_editing', 'metadata_generation'],
      },
      {
        id: 'dall-e-3',
        name: 'DALL-E 3 (High-Fidelity Image Generation)',
        capabilities: {
          textInput: true,
          textOutput: false,
          imageInput: false,
          imageOutput: true,
          imageEditing: false,
          streamingSupport: false,
          embeddings: false,
          toolCalling: false,
        },
        pricing: { imageGenerationUSD: 0.04 },
        recommendedFor: ['image_generation'],
      },
      {
        id: 'dall-e-2',
        name: 'DALL-E 2 (Image Generation & Generative Inpainting)',
        capabilities: {
          textInput: true,
          textOutput: false,
          imageInput: true,
          imageOutput: true,
          imageEditing: true,
          streamingSupport: false,
          embeddings: false,
          toolCalling: false,
        },
        pricing: { imageGenerationUSD: 0.02 },
        recommendedFor: ['object_removal', 'image_generation'],
      },
    ],
  },

  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    type: 'cloud',
    defaultEndpoint: 'https://generativelanguage.googleapis.com/v1beta',
    authType: 'query_param', // or x-goog-api-key header
    headerName: 'x-goog-api-key',
    requestFormat: 'gemini_generate_content',
    responseFormat: 'gemini_standard',
    browserDirectSupported: true, // Google Generative Language API allows browser calls with API key
    documentationUrl: 'https://ai.google.dev/docs',
    keyPlaceholder: 'AIzaSy...',
    dataRetentionPolicy: 'standard_retention',
    capabilities: {
      textInput: true,
      textOutput: true,
      imageInput: true,
      imageOutput: true, // Imagen 3 where available
      imageEditing: false,
      streamingSupport: true,
      embeddings: true,
      toolCalling: true,
    },
    defaultModels: [
      {
        id: 'gemini-1.5-pro',
        name: 'Gemini 1.5 Pro (2M Context, Ultra Precision)',
        contextWindow: 2000000,
        maxOutputTokens: 8192,
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.0035, completionPer1k: 0.0105, imageAnalysisUSD: 0.0025 },
        isDefault: true,
        recommendedFor: ['scene_analysis', 'natural_language_editing'],
      },
      {
        id: 'gemini-1.5-flash',
        name: 'Gemini 1.5 Flash (Sub-Second Latency)',
        contextWindow: 1000000,
        maxOutputTokens: 8192,
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.00035, completionPer1k: 0.00105, imageAnalysisUSD: 0.0005 },
        recommendedFor: ['natural_language_editing', 'metadata_generation'],
      },
      {
        id: 'gemini-2.0-flash-exp',
        name: 'Gemini 2.0 Flash (Next-Gen Realtime Vision)',
        contextWindow: 1000000,
        maxOutputTokens: 8192,
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.0002, completionPer1k: 0.0008, imageAnalysisUSD: 0.0004 },
        recommendedFor: ['scene_analysis', 'natural_language_editing'],
      },
    ],
  },

  anthropic: {
    id: 'anthropic',
    name: 'Anthropic Claude',
    type: 'cloud',
    defaultEndpoint: 'https://api.anthropic.com/v1',
    authType: 'x_api_key',
    headerName: 'x-api-key',
    requestFormat: 'anthropic_messages',
    responseFormat: 'anthropic_standard',
    browserDirectSupported: false, // Anthropic API blocks browser direct origin by default with CORS unless proxy/danger header is used
    corsLimitationNote: 'Anthropic requires a backend proxy or CORS relay header (anthropic-dangerous-direct-browser-access: true) for direct browser requests.',
    documentationUrl: 'https://docs.anthropic.com/claude/reference',
    keyPlaceholder: 'sk-ant-api03-...',
    dataRetentionPolicy: 'zero_retention_api',
    capabilities: {
      textInput: true,
      textOutput: true,
      imageInput: true,
      imageOutput: false,
      imageEditing: false,
      streamingSupport: true,
      embeddings: false,
      toolCalling: true,
    },
    defaultModels: [
      {
        id: 'claude-3-5-sonnet-20241022',
        name: 'Claude 3.5 Sonnet (State of the art Vision & Reasoning)',
        contextWindow: 200000,
        maxOutputTokens: 8192,
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.003, completionPer1k: 0.015, imageAnalysisUSD: 0.004 },
        isDefault: true,
        recommendedFor: ['scene_analysis', 'natural_language_editing'],
      },
      {
        id: 'claude-3-5-haiku-20241022',
        name: 'Claude 3.5 Haiku (Lightning Fast Assistant)',
        contextWindow: 200000,
        maxOutputTokens: 8192,
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.0008, completionPer1k: 0.004, imageAnalysisUSD: 0.001 },
        recommendedFor: ['metadata_generation', 'natural_language_editing'],
      },
    ],
  },

  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    type: 'compatible_openai',
    defaultEndpoint: 'https://openrouter.ai/api/v1',
    authType: 'bearer',
    requestFormat: 'openai_chat_completions',
    responseFormat: 'openai_standard',
    browserDirectSupported: true, // OpenRouter natively supports browser requests with proper CORS headers
    documentationUrl: 'https://openrouter.ai/docs',
    keyPlaceholder: 'sk-or-v1-...',
    dataRetentionPolicy: 'zero_retention_api',
    capabilities: {
      textInput: true,
      textOutput: true,
      imageInput: true,
      imageOutput: true,
      imageEditing: false,
      streamingSupport: true,
      embeddings: true,
      toolCalling: true,
    },
    defaultModels: [
      {
        id: 'anthropic/claude-3.5-sonnet',
        name: 'Claude 3.5 Sonnet (via OpenRouter CORS)',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.003, completionPer1k: 0.015 },
        isDefault: true,
        recommendedFor: ['scene_analysis', 'natural_language_editing'],
      },
      {
        id: 'openai/gpt-4o',
        name: 'GPT-4o (via OpenRouter)',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.005, completionPer1k: 0.015 },
        recommendedFor: ['scene_analysis'],
      },
      {
        id: 'meta-llama/llama-3.2-90b-vision-instruct',
        name: 'Llama 3.2 90B Vision Instruct',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.0009, completionPer1k: 0.0009 },
        recommendedFor: ['scene_analysis', 'natural_language_editing'],
      },
    ],
  },

  groq: {
    id: 'groq',
    name: 'Groq Cloud LPU',
    type: 'compatible_openai',
    defaultEndpoint: 'https://api.groq.com/openai/v1',
    authType: 'bearer',
    requestFormat: 'openai_chat_completions',
    responseFormat: 'openai_standard',
    browserDirectSupported: true,
    documentationUrl: 'https://console.groq.com/docs',
    keyPlaceholder: 'gsk_...',
    dataRetentionPolicy: 'zero_retention_api',
    capabilities: {
      textInput: true,
      textOutput: true,
      imageInput: true, // Llama 3.2 11b/90b vision
      imageOutput: false,
      imageEditing: false,
      streamingSupport: true,
      embeddings: false,
      toolCalling: true,
    },
    defaultModels: [
      {
        id: 'llama-3.3-70b-versatile',
        name: 'Llama 3.3 70B Versatile (Ultra Fast Text)',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: false,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.00059, completionPer1k: 0.00079 },
        isDefault: true,
        recommendedFor: ['natural_language_editing', 'metadata_generation'],
      },
      {
        id: 'llama-3.2-90b-vision-preview',
        name: 'Llama 3.2 90B Vision (High-Speed Visual Analysis)',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.0009, completionPer1k: 0.0009 },
        recommendedFor: ['scene_analysis'],
      },
      {
        id: 'llama-3.2-11b-vision-preview',
        name: 'Llama 3.2 11B Vision (Lightweight & Rapid)',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.00016, completionPer1k: 0.0002 },
        recommendedFor: ['scene_analysis', 'natural_language_editing'],
      },
    ],
  },

  mistral: {
    id: 'mistral',
    name: 'Mistral AI',
    type: 'compatible_openai',
    defaultEndpoint: 'https://api.mistral.ai/v1',
    authType: 'bearer',
    requestFormat: 'openai_chat_completions',
    responseFormat: 'openai_standard',
    browserDirectSupported: true,
    documentationUrl: 'https://docs.mistral.ai',
    keyPlaceholder: 'mis_...',
    dataRetentionPolicy: 'zero_retention_api',
    capabilities: {
      textInput: true,
      textOutput: true,
      imageInput: true, // Pixtral
      imageOutput: false,
      imageEditing: false,
      streamingSupport: true,
      embeddings: true,
      toolCalling: true,
    },
    defaultModels: [
      {
        id: 'pixtral-12b-2409',
        name: 'Pixtral 12B (Multimodal Vision)',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.00015, completionPer1k: 0.00015 },
        isDefault: true,
        recommendedFor: ['scene_analysis', 'natural_language_editing'],
      },
      {
        id: 'mistral-large-latest',
        name: 'Mistral Large (Complex Reasoning)',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: false,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.002, completionPer1k: 0.006 },
        recommendedFor: ['natural_language_editing'],
      },
    ],
  },

  together: {
    id: 'together',
    name: 'Together AI',
    type: 'compatible_openai',
    defaultEndpoint: 'https://api.together.xyz/v1',
    authType: 'bearer',
    requestFormat: 'openai_chat_completions',
    responseFormat: 'openai_standard',
    browserDirectSupported: true,
    documentationUrl: 'https://docs.together.ai',
    keyPlaceholder: 'tog_...',
    dataRetentionPolicy: 'zero_retention_api',
    capabilities: {
      textInput: true,
      textOutput: true,
      imageInput: true,
      imageOutput: true, // FLUX.1 models
      imageEditing: false,
      streamingSupport: true,
      embeddings: true,
      toolCalling: true,
    },
    defaultModels: [
      {
        id: 'black-forest-labs/FLUX.1-schnell',
        name: 'FLUX.1 Schnell (High-Quality Open Image Gen)',
        capabilities: {
          textInput: true,
          textOutput: false,
          imageInput: false,
          imageOutput: true,
          imageEditing: false,
          streamingSupport: false,
          embeddings: false,
          toolCalling: false,
        },
        pricing: { imageGenerationUSD: 0.003 },
        isDefault: true,
        recommendedFor: ['image_generation'],
      },
      {
        id: 'meta-llama/Llama-Vision-Free',
        name: 'Llama Vision Free',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.0, completionPer1k: 0.0 },
        recommendedFor: ['scene_analysis'],
      },
    ],
  },

  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek AI',
    type: 'compatible_openai',
    defaultEndpoint: 'https://api.deepseek.com/v1',
    authType: 'bearer',
    requestFormat: 'openai_chat_completions',
    responseFormat: 'openai_standard',
    browserDirectSupported: true,
    documentationUrl: 'https://api-docs.deepseek.com',
    keyPlaceholder: 'sk-...',
    dataRetentionPolicy: 'zero_retention_api',
    capabilities: {
      textInput: true,
      textOutput: true,
      imageInput: false,
      imageOutput: false,
      imageEditing: false,
      streamingSupport: true,
      embeddings: false,
      toolCalling: true,
    },
    defaultModels: [
      {
        id: 'deepseek-chat',
        name: 'DeepSeek V3 (State of the Art Chat & Reasoning)',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: false,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        pricing: { promptPer1k: 0.00014, completionPer1k: 0.00028 },
        isDefault: true,
        recommendedFor: ['natural_language_editing', 'metadata_generation'],
      },
      {
        id: 'deepseek-reasoner',
        name: 'DeepSeek R1 (Chain of Thought Reasoning)',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: false,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: false,
        },
        pricing: { promptPer1k: 0.00055, completionPer1k: 0.00219 },
        recommendedFor: ['natural_language_editing'],
      },
    ],
  },

  local_ollama: {
    id: 'local_ollama',
    name: 'Local Ollama Instance',
    type: 'local',
    defaultEndpoint: 'http://localhost:11434',
    authType: 'none',
    requestFormat: 'ollama_chat',
    responseFormat: 'ollama_standard',
    browserDirectSupported: true, // Note: User needs OLLAMA_ORIGINS="*" configured in Ollama environment
    corsLimitationNote: 'Ollama requires OLLAMA_ORIGINS="*" environment variable set when running on localhost to allow browser communication.',
    documentationUrl: 'https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server',
    keyPlaceholder: 'No API key required for local instance',
    dataRetentionPolicy: 'local_zero_network',
    capabilities: {
      textInput: true,
      textOutput: true,
      imageInput: true, // llava, llama3.2-vision
      imageOutput: false,
      imageEditing: false,
      streamingSupport: true,
      embeddings: true,
      toolCalling: true,
    },
    defaultModels: [
      {
        id: 'llava:latest',
        name: 'LLaVA (Local Multimodal Vision)',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: false,
        },
        isDefault: true,
        recommendedFor: ['scene_analysis', 'natural_language_editing'],
      },
      {
        id: 'llama3.2-vision:latest',
        name: 'Llama 3.2 Vision (Local)',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: true,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        recommendedFor: ['scene_analysis'],
      },
      {
        id: 'llama3:latest',
        name: 'Llama 3 (Local Text Assistant)',
        capabilities: {
          textInput: true,
          textOutput: true,
          imageInput: false,
          imageOutput: false,
          imageEditing: false,
          streamingSupport: true,
          embeddings: false,
          toolCalling: true,
        },
        recommendedFor: ['metadata_generation'],
      },
    ],
  },
};
